### ISSUE TITLE
CloudWatch error

### ISSUE THREAD

**Issue by vubui** [alexa/skill-sample-nodejs-audio-player#1]
I got this error on the CloudWatch page when accessing the log of the lambda function: "There was an error loading Log Streams. Please try again by refreshing this page."

Eventually, I had to turn on full access for CloudWatch in the security role that was created in the previous step. The log was created after that.

**Comment by bywillyoo** [comment]
@vubui where did you turn on that full access for cloudwatch? Getting the same error and can't get the log to print

**Comment by vubui** [comment]
Step 1.i of the how-to asks you to create an AWS Role in IAM with access to Lambda and DynamoDB. You select full access for DynamoDB here, but if you scroll down a bit you will see an option for full access for CloudWatch. Select that and continue with the rest of the how-to. Hope this help.

**Comment by bywillyoo** [comment]
@vubui that helped thanks!

**Comment by rjamison** [comment]
Thanks for the heads up, I've updated the README in regards:  

9a0f8e1
