### ISSUE TITLE
Unable to import module 'index_file" 

### ISSUE THREAD

**Issue by Bschuster3434** [alexa/skill-sample-nodejs-audio-player#10]
I'm getting an error when trying to upload my file to lambda. I've created a half dozen or so Alexa apps, so I'm familar with basic troubleshooting. Here is the full error:

Unable to import module 'index_file': Error
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/stateHandlers.js:4:17)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)

I changed the name of both the index file (to index_file) and the handler (index_file.handler) to rule out other issues. I've done some research, searching these sites:

https://forums.aws.amazon.com/thread.jspa?threadID=168326
https://github.com/lorenwest/node-config/issues/275

I have yet to find a solution. I am using Windows and zipping by right clicking on all the files (including the node_modules folder) and zipping them into a file. After that, I upload this to lambda from the console. I'm not sure what else to try at this point. Any suggesting on how to troubleshoot this further?

**Comment by mefogle** [comment]
This may seem obvious, but are you sure you're zipping up the files at the right point in the hierarchy (i.e., just the contents of the "js" folder and not the folder itself)? I accidentally .zipped one level up in the hierarchy once when I was doing it manually and it took me a good 30 minutes to figure out what I was doing wrong (and it failed in precisely the same way).

**Comment by Bschuster3434** [comment]
Just to be absolutely clear, you are not supposed to zip the folder 'js', you are supposed to zip the contents themselves. Is that correct?

**Comment by mefogle** [comment]
Exactly... if you open the resulting .zip, you should see all of the ".js" files and "package.json" at the top level, along with the "node_modules" folder.

**Comment by Bschuster3434** [comment]
Alright, so I just unzipped the file and the zipped file seems to extract into a new folder that I didn't create. Is it possible that windows is creating a folder when zipping the file?

**Comment by mefogle** [comment]
It's certainly possible; in my case I wasn't using Windows, I was .zipping from the command line in Linux but I just happened to be one directory above where I was supposed to be.  
Trying it out on Windows now, if I use the "Extract All" command in Explorer, it automatically appends a generated folder to the end of the path, but inside that folder I see all of the .js files and package.json at the top level inside that folder.

**Comment by Bschuster3434** [comment]
I appreciate your help here. Yeah, I saw that doing 'Extract All' creates a folder, but I'm able to click in and see everything. This seems like a noob mistake, but I've successfully created dozens of lambda functions and never had this issue. Odd.

**Comment by Bschuster3434** [comment]
Just curious, what does the 'package.json' file do?

**Comment by mefogle** [comment]
In the case of a Lambda... pretty much nothing, I believe.  In the larger scheme of things, quite a bit - most notably, pulling down the latest version of all the dependencies when you run the "npm install" command in a more traditional node environment (see https://docs.npmjs.com/getting-started/using-a-package.json). 

In fact, this begs a larger question - did you install node in your Windows environment? If not, you wouldn't be able to run "npm install" on your local machine and, therefore, you likely wouldn't have all the dependencies you need in the node_modules folder.

**Comment by Bschuster3434** [comment]
So, I just tried something. In my original code, I changed my index file name to 'index_file', both in the source code and the lambda function. Just out of curiosity, I changed the source file name back to 'index', but not the handler. I would expect it to produce the same error... but it gave something slightly different:

Unable to import module 'index_file': Error
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)

In this case, the reason for the error is because the file simply doesn't exist.

So maybe the error is truly that the file can't be uploaded? I'm going to look at my code again and see what's happening.

**Comment by mefogle** [comment]
As a follow-up to the previous comment, I followed the steps on "Step 1" of the "Readme" and ended up with the following sub-folders in the "node_modules" folder after "npm install" : 
     alexa-sdk, aws-sdk, base64-js, buffer, crypto-browserify, ieee754, isarray, jmespath, lodash, sax, xml2js, xmlbuilder
The size of the resulting .zip file is about 1.6 MB (when run from a Linux command line), if you're seeing something much smaller than this, then you probably don't have all of the dependencies that npm install should download.

**Comment by alexa-ai** [comment]
I use windows. Lesson learned after spending an hour to resolve this issue --> If you are a window user, install node.js and npm using https://nodejs.org/en/#download. (If you have mac, brew install node will work). Only after this, you will be able to do npm install. 

I am getting different error now. But, I passed the initial hurdles after npm install, then zip is done. If you are a window user, getting zip done in command line is another fun experiment.

**Comment by imamatory** [comment]
Some npm packages needs to be compiled on target platform. I've got similar issue caused by its.
