### ISSUE TITLE
where alexa read or write data from dynamoDB question

### ISSUE THREAD

**Issue by plvz** [alexa/skill-sample-nodejs-audio-player#101]
Hello, 

I tried the multiple-streams skill but I don't find where the skill read or write data from dynamoDB.
I don't get an error but my data are not saving well in my dynamoDB probably because I don't know what partition key choose.

**Comment by sebsto** [comment]
The Alexa SDK for NodeJS creates the table automatically at first read.  The two [interceptors](https://github.com/alexa/skill-sample-nodejs-audio-player/blob/mainline/multiple-streams/lambda/src/index.js#L404)  is where the skill tells the SDK to save or to read data from DynamoDB
