### ISSUE TITLE
Testing Issue

### ISSUE THREAD

**Issue by rfranks263** [alexa/skill-sample-nodejs-audio-player#102]
I keep getting stuck at the testing- 
    tvc-macbookair-05:lambda RFranks$ npm test

> skill_sample_nodejs_sdkv2_single_stream@2.0.0 test /Users/RFranks/Project/skill-sample-nodejs-audio-player-sdkv2/single-stream/lambda
> AWS_REGION=us-east-1 /usr/local/bin/mocha -r ts-node/register test/test*.ts

sh: /**usr/local/bin/mocha: No such file or directory**
npm ERR! Test failed.  See above for more details.

I'm not sure what Im missing

**Comment by benappware** [comment]
As docs [say/ imply](https://github.com/alexa/skill-sample-nodejs-audio-player/tree/mainline/single-stream#local-tests) you need to [install Mocha](https://mochajs.org/#installation).
