### ISSUE TITLE
Unable to ENQUEUE the track in the playlist to autoplay

### ISSUE THREAD

**Issue by ananddevsingh** [alexa/skill-sample-nodejs-audio-player#104]
Hi,

I'm using the sample code of audio playlist from here multiple-streams and I'm unable to modify it and implement the functionality of autoplay.

I just want the skill to play the next track from the playlist once the current track is finished playing.

I've already tried implementing the "playBehavior":"ENQUEUE" but then it stops even paying the audio.

Any help will be highly appreciable.

**Comment by sebsto** [comment]
Using the ENQUEUE parameter is the correct way to add an item to the queue 

Doc :  https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#play 
Code Sample : https://github.com/alexa/skill-sample-nodejs-audio-player/blob/mainline/multiple-streams/lambda/src/index.js#L85

It is difficult to understand what is not working in your code.  do you have a repo to share so that I can have a look at your code ?

**Comment by ananddevsingh** [comment]
Hi @sebsto,

I'm using the same code from [here](https://github.com/alexa/skill-sample-nodejs-audio-player/tree/mainline/multiple-streams).

**Steps to reproduce the bug:**
1. Open the skill by saying Alexa, Open <invocation name>. (It starts with "Welcome to the AWS...").
2. Say Alexa, next. (It will play the 2nd audio in the list).
3. Say, Alexa, Stop. (It will stop the skill).
4. Now relaunch the skill by saying Alexa, Open <invocation name>. (It will start by saying "You were listening to XYZ Would you like to resume?").
5. Now resume the last session by saying YES. It will start playing the 2nd audio in the list. Now just leave the skill to finish the audio. Once the skill finishes playing 2nd audio. It will not auto play the 3rd audio in the playlist.

Hope the issue is clear now, I've just replaced the audio data [here](https://github.com/alexa/skill-sample-nodejs-audio-player/blob/mainline/multiple-streams/lambda/src/constants.js#L8) in the code with small audios so that you can check it easily.

`exports.audioData = [{
    title: 'A round of applause',
    url: 'https://www.sample-videos.com/audio/mp3/crowd-cheering.mp3',
  },
  {
    title: 'Big waves in the ocean',
    url: 'https://www.sample-videos.com/audio/mp3/wave.mp3',
  },
  {
    title: 'Drum beats',
    url: 'https://d9olupt5igjta.cloudfront.net/samples/sample_files/19695/f62b29e82724a8a6fd66fcd4e8c89a32e4009165/mp3/_moog.mp3'
  },
  {
    title: 'Romantic music',
    url: 'https://d9olupt5igjta.cloudfront.net/samples/sample_files/16790/9621b13a9993c90bb262ce861c24b856f2713332/mp3/_sad_lofi.mp3'
  },
  {
    title: 'End of the playlist',
    audio: 'https://d9olupt5igjta.cloudfront.net/samples/sample_files/19138/c77ac03e91a4b649aeca5ade7d1a3c514725e235/mp3/_looperman-l-1998259-0107528-adamsouth22-soft-vinyl-lofi-piano.mp3'
  }
];`

Let me know in the case of any further clarification.

**Comment by sebsto** [comment]
Thank you for the clear explanation - I will have a look

**Comment by ananddevsingh** [comment]
Hi @sebsto,
I appreciate your efforts. Did you get any success on the same?

**Comment by talkingnews** [comment]
Hi @sebsto and @ananddevsingh - this is because there is a bug in Echo devices which causes short tracks not to trigger PlaybackNearlyFinished. From my testing, this applies to tracks up to 30 seconds long. It seems like this bug is a major problem for many developers.

See https://forums.developer.amazon.com/questions/178909/about-alexa-audio-error-on-skills.html and https://amazonalexa.slack.com/archives/C2DQ0F1U0/p1534766053000100 for example.

I have also filed a bug over at UserVoice - please vote one it once it has been approved:
https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote/suggestions/35201296-send-playbacknearlyfinished-for-short-tracks-or-a

**Comment by ananddevsingh** [comment]
CC: @sebsto,

Hi @talkingnews, Thanks for your swift response. 

I' would like to make you aware that this issue is **not only** for short tracks but for long tracks too. I'm having the audio files of more than **6-12mins** but it's not working even for those.

**Comment by talkingnews** [comment]
Hi @ananddevsingh - OK, that's bad news. Do you know if this particularly affects a type of stream, like vbr for example? I used a little bit of debugging code to monitor the problem; you can try calling this function for every audioplayer event that Alexa sends.

(Note: This is for the old v1 SDK and audioplayer example - just adapt for V2!)

```
function logAudioEvent() {

console.log(`
this.event.request.type ${this.event.request.type}
this.event.context.AudioPlayer.playerActivity ${this.event.context.AudioPlayer.playerActivity}
this.event.session.attributes.playbackIndexChanged ${this.event.session.attributes.playbackIndexChanged}

this.event.request.offsetInMilliseconds ${this.event.request.offsetInMilliseconds}
this.event.context.AudioPlayer.offsetInMilliseconds ${this.event.context.AudioPlayer.offsetInMilliseconds}
this.event.session.attributes.offsetInMilliseconds ${this.event.session.attributes.offsetInMilliseconds}

this.event.session.attributes.index ${this.event.session.attributes.index}
this.event.request.token ${this.event.request.token}
this.event.context.AudioPlayer.token ${this.event.context.AudioPlayer.token}
this.event.session.attributes.token ${this.event.session.attributes.token}
this.attributes['playbackFinished'] ${this.attributes['playbackFinished']} 
this.attributes['enqueuedToken'] ${this.attributes['enqueuedToken']}
`);
}
```

**Comment by allthepies** [comment]
Same issue as this one:
https://github.com/alexa/skill-sample-nodejs-audio-player/issues/115

The fix I posted should resolve.

**Comment by ananddevsingh** [comment]
Thank you so much team. I confirm, the issue is fixed now.

**Comment by piyushaggarwal-mob-incedo** [comment]
> CC: @sebsto,
> 
> Hi @talkingnews, Thanks for your swift response.
> 
> I' would like to make you aware that this issue is **not only** for short tracks but for long tracks too. I'm having the audio files of more than **6-12mins** but it's not working even for those.

Yes

**Comment by piyushaggarwal-mob-incedo** [comment]
@ananddevsingh 

How are you able to resolve this issue. Can You please help. In My Case

PlaybackNearlyFinished is not calling at the end of the stream. It is just calling as soon as Alexa.PlaybackStarted event is fired. I want to load the next audio but PlayBackNearlyFinished  is not calling at the end of audio stream. My Audio is 5-30 minites long. Please help. I am working with Alexa SDK

**Comment by sebsto** [comment]
Please, bear in mind that, according to documentation, PlaybackNearlyFinished is not sent when the stream is about to end, it is send **as soon as the device is ready to receive an enqueue directive** (see https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#playbacknearlyfinished : "Sent when the device is ready to add the next stream to the queue." )
So event delivery timing might depend on the device.  Devices with more memory will be ready sooner than others.

Appropriate response is to ENQUEUE the next stream with a PlayDirective, it does not matter if this is done at the beginning of your stream or close to the end.  The device will enqueue the next stream and play it when current stream will be finished.

Seb
