### ISSUE TITLE
unable to setup  AudioPlayer 

### ISSUE THREAD

**Issue by swathionchip** [alexa/skill-sample-nodejs-audio-player#111]
Hi ,

I am unable to setup and run the code.
Please guide me how to set up this code.

Regards,
Swathi.

**Comment by sebsto** [comment]
Hello

I am sorry to learn you have problem with this code sample. Would you mind sharing a bit more details like the exact step by steps instructions to reproduce the problem and any relevant error message ?

Thank you

**Comment by swathionchip** [comment]
Hi,

I followed the below steps

1) Download the code from "https://github.com/alexa/skill-sample-nodejs-audio-player.git"
2) Extract the zip folder and take the multiple-streams folder.
3) open command prompt go to the multiple-streams path and I gave the ask deploy.

**C:\Users\swathi\sample\multiple-streams>ask deploy
-------------------- Update Skill Project --------------------
Skill Id: amzn1.ask.skill.d15de3a5-547b-40be-8473-d6a24c6f8c02
Skill deployment finished.
Model deployment finished.
Lambda deployment finished.
Lambda function(s) updated:
  [URI] arn:aws:lambda:us-east-1:884201671301:function:ask-custom-Multi_Stream_Audio_Player
No in-skill product to be deployed.
Your skill is now deployed and enabled in the development stage.
Try invoking the skill by saying “Alexa, open {your_skill_invocation_name}” or simulate an invocation via the `ask simulate` command.**

4) After deploying, added the DynamoDB permission to the IAM Role created to execute your function :

5) Change the skill id in lambda code 
command : ask api list-skills
 I got the skill id and paste in to lambda/src/constants.js file.

6) I run the audio player in alexa emulator in windows .

user : alexa, open open audio player

Alexa : Welcome to the AWS Podcast. you can ask to play the audio to begin the podcast.

User : begin the podcast

alexa : This is Episode 139

![image](https://user-images.githubusercontent.com/29200388/41334089-df4287c4-6f01-11e8-9118-1c5f76368519.png)


7) I tested the this skill in my raspberry pi3  board here I am getting "sorry something went wrong" from Alexa device.

How to test to my skill in raspberry Pi3 board.


Regards,
Swathi.

**Comment by sebsto** [comment]
Hello. Thank you for the detailed description. 
From the messages below it looks like everything is working as expected. 
Audio skills are not working in the web simulator. 
AVS devices might or might now work. Depending on the implementation it might accept audio streaming or not. 
To test the full experience you need to test from
an actual Echo device. 

--Seb

**Comment by swathionchip** [comment]
Hi,

I need to test audio skill in my PI3 board.
How to I test the skill in the rasberry pi3 board.

I am asking alexa, open audio player.
it is giving "sorry something went wrong " 


Regards,
Swathi.

**Comment by sebsto** [comment]
You can not test the skill from a Raspberry Pi.  Audio Player skills only work on Amazon Echo devices and selected third party devices.
