### ISSUE TITLE
Get permission from Amazon to enable Amazon Music skill on a third party device.

### ISSUE THREAD

**Issue by swathionchip** [alexa/skill-sample-nodejs-audio-player#112]
We are integrating Alexa into a commercial product and want to enable Amazon Music skill. It seems third party devices need permission from Amazon to enable Amazon skill. How to apply for a permission from Amazon?

**Comment by sebsto** [comment]
Hello,

Thank you for your interest for Amazon Alexa.  This repository is about code sample for audio player skill.  This is not the right vehicle to ask general questions about Alexa development, partnerships or Music Skill.  

As your integration is not related to the code sample posted here, I would suggest you to post your question to the general Alexa developer forum instead.  https://forums.developer.amazon.com/spaces/165/index.html 

Seb
