### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by somakolli** [alexa/skill-sample-nodejs-audio-player#113]
In File lambda/src/utils/RadioRequestHandler.ts line 5 it should be './**i**Handler' instead of '/.**I**Handler'.

**Comment by sebsto** [comment]
Good catch !  MacOS is too much forgiving about these :-( 
Fixed https://github.com/alexa/skill-sample-nodejs-audio-player/commit/07aec52213105966ae66fe2b6d9dc94cb9778151
