### ISSUE TITLE
How to test the my own custom alexa skill on my device.

### ISSUE THREAD

**Issue by swathionchip** [alexa/skill-sample-nodejs-audio-player#116]
Hi ,

I created sample Alexa custom skill and I tested in Alexa simulator it is working fine but I am unable to test this custom skill on my raspberry pi 3 board.
what is the procedure to test in my device.

I am using my amazon account for creation of Custom skill and alexa-sdk authorisation also same account in Raspberry pi 3 board 

Regards,
Swathi.

**Comment by sebsto** [comment]
Your development skill will be automaticatically enabled on your amazon account and it will be available from all devices, including AVS devices registered to this account.

I am closing this issues as the question is not related the an issue with the source code in this repository.

For general help, please feel free to ask your questions in the Alexa developer forums at https://forums.developer.amazon.com/index.html
