### ISSUE TITLE
how to know which echo device is using my alexa custom skill

### ISSUE THREAD

**Issue by swathionchip** [alexa/skill-sample-nodejs-audio-player#117]
Hi All,

I wrote my own Alexa custom skill and I can access from different echo device that are are associated with my amazon account but How to I known which echo device is accessing my custom skill.

Thanks In Advance.

Regards,
Swathi.

**Comment by sebsto** [comment]
In the request sent to your skill, there is a device ID passed as parameter. Your skill code can track these.  These are stable as long as customer do not disable your skill.
If you need to know the location or name of the device, your skill must ask the customer "It looks like it is the first time you are using SKILL_NAME on this device.  What is the name of this device?"
You can use a database, such as AWS DynamoDB, to keep track of user devices and names.

**Comment by swathionchip** [comment]
Thanks Sebsto, for reply.

I don't want to track my skill. I need to identify the device and restrict the skill to use, if it is not my device.

See my new question https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/455

**Comment by sebsto** [comment]
This will not be possible. Your skill just receive a anonymized device id. you can’t restrict a skill per device. This is not the philosophy of Alexa, a personal assistant, available anytime and anywhere. Whatever device customer is using to talk to Alexa (from amazon or a third party), customer will have the same experience, the same skills and the same answers
