### ISSUE TITLE
My AudioPlayer Alexa Skill doesn't load the mp3 from given URL quickly.

### ISSUE THREAD

**Issue by djhrishi19** [alexa/skill-sample-nodejs-audio-player#118]
I've created a custom podcast skill for my podcast. But it doesn't load the audio file quickly. It takes time and sometimes doesn't play at all. Initially I thought that it was the WiFi problem. But when I play podcasts like The Dave Ramsey Show etc, they load and start instantly.

My hosting site is libsyn.
Audio URL in form : "https://traffic.libsyn.com/secure/XYZ-ep02.mp3

The skill is not live yet. But does anybody know why this is happening?

**Comment by djhrishi19** [comment]
Can anybody figure this out please?? I'm stuck...

**Comment by ronnypringels** [comment]
![image](https://user-images.githubusercontent.com/1623233/44746607-2182a480-ab0b-11e8-8d7a-ad87c0f72a09.png)

**Comment by djhrishi19** [comment]
This happened because it was not the actual link... It was just an example.. The actual link is 
https://traffic.libsyn.com/secure/theinspiringtalk/TIT_49_Best_of_TIT.mp3  
But these still take time..

**Comment by mefogle** [comment]
I wonder whether the 302 redirect isn't part of the issue here.  Did you try using the final destination URL (e.g., https://secure-hwcdn.libsyn.com/p/e/3/c/e3c1c5678a3215bf/TIT_49_Best_of_TIT.mp3?c_id=22925937) to see whether that's more reliable? I don't expect that will be a solution, but at least it might help you narrow down where the problem is.

**Comment by djhrishi19** [comment]
How did you find the final destination URL?

**Comment by mefogle** [comment]
In this case I just entered the original URL into a browser, copied the URL it redirected to, and took most of the additional parameters off of the end of it. 
Doing so programatically would require a bit more work - you'd probably need to use a library like request (https://github.com/request/request) to place a GET request to the original URL and then obtain the eventual location from the response.

**Comment by aszk** [comment]
@djhrishi19  If you still have the issue, please feel free to [contact us ](alexa.design/contactus)
