### ISSUE TITLE
How to prompt and retrieve the slot value from lambda function

### ISSUE THREAD

**Issue by swathionchip** [alexa/skill-sample-nodejs-audio-player#119]
Hi All,

How to prompt for slot value from lambda function and the response will be taken from lambda function without specifying in alexa skill as required slot.

Thanks in advance.

Regards,
Swathi.

**Comment by allthepies** [comment]
Is this a general question or an issue with the audio player example ?

**Comment by sebsto** [comment]
Closing as this is not a question related to the audio sample.  Please post general alexa question to the Alexa developer forum at https://forums.developer.amazon.com/spaces/23/index.html 

The answer for your question is about slot management and elicitation.  Documentation is here : https://developer.amazon.com/blogs/alexa/post/5fe7565a-9547-4e03-be36-6c62ed356d57/dynamically-elicit-slots-during-dialog-management-based-on-previously-given-slot-values
