### ISSUE TITLE
DynamoDB error

### ISSUE THREAD

**Issue by dreed47** [alexa/skill-sample-nodejs-audio-player#12]
I get the following error while trying to run the sample.

`Error during DynamoDB put:ResourceNotFoundException: Requested resource not found`

I followed the instructions and tried several different roles all of which have the "AmazonDynamoDBFullAccess" policy.  I even tried manually creating the DynamoDB table and I get the same error.

**Comment by dreed47** [comment]
dup issue

**Comment by sc5606** [comment]
Hello "dreed47", were you able to resolve this issue? I am also stuck at this point.
