### ISSUE TITLE
aws configure doesn't work?

### ISSUE THREAD

**Issue by needforspeed** [alexa/skill-sample-nodejs-audio-player#124]
Following the README in the single-stream, but aws configure doesn't seem to work
```bash
➜  single-stream aws configure // https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: argument subcommand: Invalid choice, valid choices are:

list                                     | get
set                                      | add-model
```

**Comment by sebsto** [comment]
The URL after the `//` is a comment to show you where to find the documentation on AWS CLI.
The command to type is `aws configure`

I modified the README to avoid confusion in the future
https://github.com/alexa/skill-sample-nodejs-audio-player/commit/73dbf564611293741b9ed6540ff18e8b5ea5ade5
