### ISSUE TITLE
Incorrect help track speech

### ISSUE THREAD

**Issue by allthepies** [alexa/skill-sample-nodejs-audio-player#126]
Shouldn't:

https://github.com/alexa/skill-sample-nodejs-audio-player/blob/0021ba623c07b3d14ffbc189f238d417bb6be24e/multiple-streams/lambda/src/index.js#L340

Be:

`message = 'You were listening to ${constants.audioData[playbackInfo.playOrder[playbackInfo.index]].title}. Would you like to resume?;'`

i.e. add the playOrder[playbackInfo.index] in case the user had enabled shuffle and the track order was not sequential.  This is how the same speech output in the launch intent handler works.

(Had to change quotes to get code to post properly but you get the idea)

**Comment by sebsto** [comment]
Thank you for the suggestion and catching this.  Can you submit a pull request to keep attribution in the code ?

**Comment by aszk** [comment]
Closing because this sample code is recreated.
