### ISSUE TITLE
Connect's multiple times

### ISSUE THREAD

**Issue by Devil-of-Chaos** [alexa/skill-sample-nodejs-audio-player#128]
If I start the skill it is connection 3 times to the streaming server.

I'm using the single stream project.

If I say Alexa, stop it is stopping finde but the client(s) stay connected
![unbenannt](https://user-images.githubusercontent.com/1410820/48777802-e049fd00-ecd3-11e8-95db-7c1d02d6ebf7.PNG)

**Comment by aszk** [comment]
Do you still have the issue? I'd recommend [contacting us](alexa.design/contactus) to further investigation. I am closing this at this time.
