### ISSUE TITLE
M3U Issue

### ISSUE THREAD

**Issue by tomhiggins** [alexa/skill-sample-nodejs-audio-player#13]
When an m3u is used as the source media in audioAssets.js all the links in that m3u  are treated by AudioPlayer as one item. When the user asks for the next item it disregards the rest of the items in the m3u and goes on to the next item listed in the audioAssests.js

Is this as intended or is there a way to treat m3u items as items.

**Comment by talkingnews** [comment]
Hi @tomhiggins  - did you ever get this resolved or figure something out?

**Comment by sebsto** [comment]
Earlier device firmware where not correctly handling M3U files (and HLS format in general) - This should be fixed now.  Let us now if the problem happens again.

I am closing this thread as it does not appear to be a problem with the code sample.
