### ISSUE TITLE
Can you add example of the new music skill?

### ISSUE THREAD

**Issue by needforspeed** [alexa/skill-sample-nodejs-audio-player#132]
I see there is a new music skill

https://developer.amazon.com/docs/music-skills/understand-the-music-skill-api.html#introduction

Is it possible to enrich the example for music skill?

What's the catalog role?  I'm asking because I don't see catalog being mentioned here in this repo.

**Comment by aszk** [comment]
We currently don't have a plan to create sample code for Music, Radio, and Podcast Skill API.
Please refer the document for more details. https://developer.amazon.com/en-US/docs/alexa/music-skills/catalog-reference.html
If you have further question, please feel free to [contact us](alexa.design/contactus)
