### ISSUE TITLE
Adding additional streams to template

### ISSUE THREAD

**Issue by PMR1158** [alexa/skill-sample-nodejs-audio-player#133]
Was hoping someone could offer some guidance on how to add additional streams to the template. Unfortunately, I don't know much about code but I'm trying to learn. I tried adding more links to the audio assets list but apparently it's not that simple. I can change the two podcast URL's to mp3's I have stored in an S3 bucket and they play just fine. But I can't figure out how to increase the number of streams the skill will play beyond two. I think it's because the code won't recognize additional streams until tokens have been assigned but that's just a guess and if that is the problem, I'm not sure how it's done. Thanks in advance for any guidance you're willing to offer!

**Comment by armonnaeini** [comment]
Hi, this got closed, but what is your solution? I am just now trying to learn how to develop skills, and I am trying to use multiple audio files that are stored on a server.

**Comment by PMR1158** [comment]
It's been a while but I believe the solution was to add all the new stream url's to the lambda/src/constants.js file BEFORE initially deploying the skill. That way when the DynamoDB table is first created upon skill deployment it sets up the play order list with the right number of tokens which in my case was 12. ![DynamoDB](https://user-images.githubusercontent.com/45274157/56007440-b905c380-5ca6-11e9-8f54-57fe29cd5137.png)

**Comment by PMR1158** [comment]
![DynamoDB](https://user-images.githubusercontent.com/45274157/56007351-6cba8380-5ca6-11e9-967c-6876e2abddaa.png)

**Comment by aszk** [comment]
Please refer https://github.com/alexa-samples/skill-sample-nodejs-multistream-audio-player for multiple stream.
