### ISSUE TITLE
For what is DynamoDB

### ISSUE THREAD

**Issue by kkorinna** [alexa/skill-sample-nodejs-audio-player#141]
Hi guys, 

For what exactly is DynamoDB needed by the development of an audio stream skill (multiple streams)?

Thx in advance

Br,
Korinna

**Comment by cczhong11** [comment]
Save status of the audio player after stop, in order to help you resume the audio from the last time.

**Comment by Mohd-Aamir-M** [comment]
There is no necessity of using DynamoDB, it's a recommended suite of stack by AWS. You can save state in any Relational Database or NoSQL.

**Comment by EOskuee** [comment]
Hi every one,
how can we remove the DynamoDB from our skill code with no error?
tnx

**Comment by aszk** [comment]
I'd recommend creating new audio player skill from scratch. The purpose of using DynamoDB is save status of the audio, like cczhong11 mentioned. This repository uses persistent(DynamoDB) almost everywhere including just playing an audio. The audio player skill needs to handle PauseIntent and ResumeIntent, so some data persistent is necessary. https://developer.amazon.com/en-US/docs/alexa/custom-skills/audioplayer-interface-reference.html#config
