### ISSUE TITLE
Message at Line 365 Not Playing

### ISSUE THREAD

**Issue by PMR1158** [alexa/skill-sample-nodejs-audio-player#142]
When exiting multi-stream with STOP or CANCEL, the verbal response at lambda/src/index.js/line 365 does not play however, the audio stream does stop. Shouldn’t the player allow a custom exit message .speak (‘ANY TEXT’) or am I using the wrong commands to invoke the message?

**Comment by aszk** [comment]
Closing this issue because related case is closed and this is not relevant to new sample code.
