### ISSUE TITLE
Cannot set property 'loop' of undefined

### ISSUE THREAD

**Issue by PMR1158** [alexa/skill-sample-nodejs-audio-player#143]
Getting this message when running bespoken test from command line

console.log lambda\src\index.js:394
Error handled: Cannot set property 'loop' of undefined

Could someone please help me identify the problem? Thanks

**Comment by PMR1158** [comment]
It appears to be a problem with Persistence w/ DynamoDB / AMAZON.NextIntent but I can't figure it out. All that was changed in the lambda/src/constants.js file was to add more tracks (total of 12) and in the lambda/src/index.js file, I revised the prompts Alexa speaks and changed the value in line 551 from 10 to 11 since I believe it should match the value of the last token in play order list? When it starts from the beginning, or from any track except the last one, it works fine and the next, previous, pause, resume, start over & shuffle commands all perform as expected. The issue occurs when it reaches the next-to-last track, either sequentially or via the next or shuffle commands. That's when it locks up and won't accept any commands including the skill invocation and at that point, I have to disable the skill with the Alexa app & then re-enable to get it working again. I checked the DynamoDB table & there are 12 entries in the playorder list (0-11) to accommodate the 12 tracks. I've put a lot of effort into searching for a fix but I'm really stuck at this point & would greatly appreciate some help in figuring it out. Here are the bespoken test results...

BST: v2.3.7  Node: v8.10

console.log lambda\src\index.js:394
    Error handled: Cannot set property 'loop' of undefined

  console.log lambda\src\index.js:394
    Error handled: Cannot set property 'loop' of undefined

 FAIL  test\unit\intents.test.yml
  en-US
    Launch request, no further interaction.
      √ LaunchRequest
      √ AMAZON.StopIntent
    Launch request and start playing audio.
      √ PlayAudio
      √ AMAZON.StopIntent
      √ AMAZON.ResumeIntent
    Pause audio and resume.
      √ LaunchRequest
      √ PlayAudio
      √ AMAZON.PauseIntent
      √ AMAZON.ResumeIntent
      √ AMAZON.StopIntent
    Cancel.
      √ LaunchRequest
      √ PlayAudio
      √ AMAZON.CancelIntent
      √ AMAZON.ResumeIntent
      √ AMAZON.StopIntent
    Start audio, next track, previous track, stop.
      √ LaunchRequest
      √ PlayAudio
      √ AMAZON.NextIntent
      √ AMAZON.PreviousIntent
      √ AMAZON.NextIntent
      √ AMAZON.StopIntent
    Persistence with DynamoDB.
      √ LaunchRequest
      √ PlayAudio
      × AMAZON.NextIntent
    Handles AMAZON.ShuffleOnIntent.
      √ LaunchRequest
      √ PlayAudio
      √ AMAZON.ShuffleOnIntent
    Handles AMAZON.ShuffleOffIntent.
      √ LaunchRequest
      √ PlayAudio
      √ AMAZON.ShuffleOffIntent
    Handles AMAZON.LoopOnIntent.
      √ LaunchRequest
      √ PlayAudio
      √ AMAZON.LoopOnIntent
    Handles AMAZON.LoopOffIntent.
      √ LaunchRequest
      √ PlayAudio
      √ AMAZON.LoopOffIntent
    Start audio, previous track till the beginning of the list
      √ LaunchRequest
      √ PlayAudio
      √ AMAZON.PreviousIntent
      × AMAZON.PreviousIntent
    Start audio, next track till the end of the list
      √ LaunchRequest
      √ PlayAudio
      √ AMAZON.NextIntent
      × AMAZON.NextIntent

  ● en-US › Persistence with DynamoDB. › AMAZON.NextIntent

    Expected value at [response.outputSpeech.ssml] to ==
        You have reached the end of the playlist
    Received:
        <speak>Apollo 8</speak>

      77 |   - $..audioItem.stream.url: "https://s3.amazonaws.com/pmramp/Apollo+7.mp3"
      78 | - AMAZON.NextIntent:
    > 79 |   - response.outputSpeech.ssml: You have reached the end of the playlist
      80 |   - response.shouldEndSession: undefined
      81 |   - response.directives[0].type: AudioPlayer.Stop
      82 |

      at test/unit/intents.test.yml:79:0
      Timestamp:
        2019-04-14T10:25:48.071

  ● en-US › Start audio, previous track till the beginning of the list › AMAZON.PreviousIntent

    Error
      Expected value at [prompt] to ==
        You have reached the start of the playlist
      Received:
        <speak>President John F. Kennedy. Rice;Stadium. September 12, 1962</speak>

      Timestamp:
        2019-04-14T10:25:48.197

  ● en-US › Start audio, next track till the end of the list › AMAZON.NextIntent

    Error
      Expected value at [prompt] to ==
        You have reached the end of the playlist
      Received:
        <speak>Apollo 8</speak>

      Timestamp:
        2019-04-14T10:25:48.226

 PASS  test\unit\audioPlayerRequests.test.yml
  en-US
    Test PlaybackNearlyFinished and PlaybackFinished
      √ LaunchRequest
      √ PlayAudio
      √ AudioPlayer.PlaybackNearlyFinished
      √ AudioPlayer.PlaybackFinished

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |    84.89 |     76.6 |      100 |    84.89 |                   |
 index.js |    84.89 |     76.6 |      100 |    84.89 |... 05,526,527,529 |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 passed, 2 total
Tests:       3 failed, 10 passed, 13 total
Snapshots:   0 total
Time:        4.37s
Ran all test suites.

**Comment by PMR1158** [comment]
Total of 12 tracks - after issuing Alexa a stop command at the very end of tracks 1, 2, 3, 4, 5, 6, 7, 8, 9 & 10 (token #'s 0-9) DynamoDB table shows Next Stream Enqueued = TRUE with matching index and token values as shown in 1'st screenshot below. However, after stopping next to last track 11 (token #10) just before end of track, table shows Next Stream Enqueued = False with a correct token value of 10 but an index number of -1 as shown in the 2'nd screenshot. And finally, when allowing next to last track (token #10) to play all the way through, at which time skill hangs before playing final track (token #11) table shows an index number of 11 but a token value of 10 as shown in the last screenshot. Can anyone explain what might be preventing the last track from playing based on screenshots of the DynamoDB table shown below?

![track 1](https://user-images.githubusercontent.com/45274157/52538546-04046880-2d42-11e9-85f2-5d8d62fa9228.jpg)
![track 11](https://user-images.githubusercontent.com/45274157/52538563-34e49d80-2d42-11e9-9109-0049d10264e2.jpg)
![Hangs](https://user-images.githubusercontent.com/45274157/56095186-364c5680-5ea8-11e9-89d6-ee9b937778f6.png)

**Comment by PMR1158** [comment]
Here's the log output received when running the failed NextDB test event on AWS lambda console. Execution results for other configured test events (Launch, NextIntent, NoAudio & PlayAudio) are all successful.

START RequestId: 9dfb2bec-14ad-4401-8b51-c6c7d62a3b47 Version: $LATEST
2019-04-14T14:51:00.647Z	9dfb2bec-14ad-4401-8b51-c6c7d62a3b47	{"errorMessage":"Cannot read property 'System' of undefined","errorType":"TypeError","stackTrace":["CustomSkill.<anonymous> (/var/task/node_modules/ask-sdk-core/dist/skill/CustomSkill.js:97:74)","step (/var/task/node_modules/ask-sdk-core/dist/skill/CustomSkill.js:44:23)","Object.next (/var/task/node_modules/ask-sdk-core/dist/skill/CustomSkill.js:25:53)","/var/task/node_modules/ask-sdk-core/dist/skill/CustomSkill.js:19:71","new Promise (<anonymous>)","__awaiter (/var/task/node_modules/ask-sdk-core/dist/skill/CustomSkill.js:15:12)","CustomSkill.invoke (/var/task/node_modules/ask-sdk-core/dist/skill/CustomSkill.js:78:16)","/var/task/node_modules/ask-sdk-core/dist/skill/factory/BaseSkillFactory.js:99:27"]}
END RequestId: 9dfb2bec-14ad-4401-8b51-c6c7d62a3b47
REPORT RequestId: 9dfb2bec-14ad-4401-8b51-c6c7d62a3b47	Duration: 21.12 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 78 MB

**Comment by aszk** [comment]
Closing because relevant issue was resolved.
