### ISSUE TITLE
Getting Error reterving device rendering

### ISSUE THREAD

**Issue by nidhinkumar06** [alexa/skill-sample-nodejs-audio-player#144]
I am using the audio player skill while testing i am getting the error as 
``` Error retrieving device rendering.```
 The audios are of mp3 format which is stored in s3.
I have added DynamoDB also
Though i have skills created using audio player earlier but i am having the issue in this skill.
Even the data is not getting shuffled once the skill is started to play and again if i open the skill it shows the same skill again and again.

**Comment by dotupNET** [comment]
I had the same problem. For me it was a small mistake: "ShouldEndSession" was set to true in the launch request

**Comment by DheerajArora5** [comment]
I had the same issue. It was related to - this.response.cardRenderer function ,fixed this with the arguments as  ('text','text',cardImageObject).

**Comment by aszk** [comment]
This issue came from old version of the sample. Please let me know if the issue still persists with new sample code.
