### ISSUE TITLE
Add German language

### ISSUE THREAD

**Issue by martinorob** [alexa/skill-sample-nodejs-audio-player#146]
Please can anyone tell me how I can add the German Language of my radio existing skill?

I have read this but doesn't works..

https://developer.amazon.com/it/blogs/alexa/post/08c5d3cb-8d0e-4241-8504-6d16eb4f194b/how-to-update-your-alexa-skills-for-spain

Thanks

**Comment by martinorob** [comment]
no one?
please

**Comment by aszk** [comment]
We don't have a plan to add de-DE locale to the repository. However you can add de-DE locale on your own following the blog post.
