### ISSUE TITLE
Has support for this skill template been discontinued?

### ISSUE THREAD

**Issue by PMR1158** [alexa/skill-sample-nodejs-audio-player#147]

**Comment by ghost** [comment]
Looks like it - it's very out of date now. A shame.
Mlopezr has done some good work to fix some errors https://github.com/mlopezr/skill-sample-nodejs-audio-player/tree/mainline/multiple-streams

**Comment by aszk** [comment]
Sorry for the late response. We updated the entire code and the current version is supported.
