### ISSUE TITLE
[Error]: Please provide the uri (either ARN or function name if using Lambda) for custom/default.

### ISSUE THREAD

**Issue by bharathpgp** [alexa/skill-sample-nodejs-audio-player#148]
Error during ASK CLI deployment

**Comment by PMR1158** [comment]
I remember seeing this error before but can't recall the circumstances. I do know the ARN of your lambda function - listed top right of the Amazon Web Services, ask-custom-Multi_Stream_Audio_Player function page - should be listed inside quotes ("uri": "ARN GOES HERE") on lines 11 and 34 of the .ask config file.

Deployment of this code sample can be tricky and you must follow the Readme file exactly. Prior to deployment, you must run (npm install) from a command line while in the skill's lambda directory to install the required dependencies. Then following successful deployment, be sure to add DynamoDB FullAccess permission to the IAM role of your function.

Good luck and hope you get it working...

**Comment by franklin-lobb** [comment]
Add the URI value under the endpoint in your skill.json.  Here's an example from the fact skill: https://github.com/alexa/skill-sample-nodejs-fact/blob/63cc94afe0214319b2504300d78420bde0f7ada4/skill.json#L163
