### ISSUE TITLE
ProgressBar issue

### ISSUE THREAD

**Issue by sharanken** [alexa/skill-sample-nodejs-audio-player#149]
Hey In my audio player skill It is not showing the audio play time. Is there anything I should do 
to show the duration of the audio.

**Comment by muhammad-ramzan-confiz** [comment]
Hello I am facing this issue of progress bar not showing while playing audio. Also there is no information of play time of audio file.
I have seen Amazon music skill a progress bar is displayed over there.
How can I display progress bar?
Regards,

**Comment by sharanken** [comment]
There Is no information on how to to that. For now, I think it is not possible.

**Comment by cargiggles** [comment]
The progress bar, as you might see when streaming from Amazon Music on your Echo Show, is not currently a supported feature of the AudioPlayer interface used in custom skills.
