### ISSUE TITLE
Next and Previous not working

### ISSUE THREAD

**Issue by jasonhendrix** [alexa/skill-sample-nodejs-audio-player#15]
Using the code as is with no changes, I am able to get it to play the audio but the Next and Previous commands both result in:
There was a problem with the requested skills response.

At the same time, the CloudWatch logs show:
Task timed out after 3.00 seconds

**Comment by sebsto** [comment]
Alexa timeout is 8 secs, so it is a best practice to configure Lambda timeout to 7 secs, instead of the 3 secs by default.
