### ISSUE TITLE
jump forward 5 min

### ISSUE THREAD

**Issue by nskoro** [alexa/skill-sample-nodejs-audio-player#150]
Can you add an example of how to use the skip forward feature? Pretty please. The official documentation is confusing as can be.

**Comment by talkingnews** [comment]
I'm afraid there's no such feature available for custom skills. Despite years of requests, only Amazon's own Audible skill has this feature. To implement it, you have to write your own time-skipping handler, and the user has to perform a full invocation. In other words, the user cannot say "alexa, jump forward 5 minutes", they always have to say "alexa, ask podcastsplayer (or whatever) to jump forward 5 minutes".

If you think it would be better to remove that extra step, please vote here!
https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote/suggestions/33406042-remove-requirement-for-invocation-name-when-an-aud


https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#intents

**Comment by nskoro** [comment]
I see, thanks for the explanation. voted.

**Comment by aszk** [comment]
Closing. Answered by community.

**Comment by yann-papouin** [comment]
[https://alexa.uservoice.com](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote/suggestions/35102689-add-fast-forward-and-rewind-to-the-skill-that) is no more, you are now redirected to an helpdesk form ... nice user voice.

**Comment by aszk** [comment]
@yann-papouin We are no longer accepting new feature request submissions through UserVoice. Please send any new requests https://developer.amazon.com/alexa/console/contact-us
