### ISSUE TITLE
help me to create dynamo table and iam user for this skill

### ISSUE THREAD

**Issue by gabbiano69** [alexa/skill-sample-nodejs-audio-player#152]
i upload a zip file to lambda because i can't use ask cli to depoly..
but i don't know ho to create table in dynamo and iam user but specially i don't know how to connect them to my lambda function

**Comment by aszk** [comment]
Please refer these document.
- https://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStartedDynamoDB.html

If you want to use Alexa-hosted, please see the below.
- https://developer.amazon.com/en-US/docs/alexa/hosted-skills/alexa-hosted-skills-session-persistence.html

Closing this but let me know if you have further question.
