### ISSUE TITLE
InvalidParameterValueException: The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions.

### ISSUE THREAD

**Issue by egilchri** [alexa/skill-sample-nodejs-audio-player#154]
I get this error when I try to do a 

`ask deploy`

Seems like it should be simple, but I'm missing something.  I was using an earlier version of Node js on my laptop, but have since upgraded. Can you tell me how I can set the runtime parameter for the version of Nodejs?

**Comment by aszk** [comment]
I updated nodejs runtime from 12.x to 16.x. You can use current [ask-resources.json](https://github.com/alexa-samples/skill-sample-nodejs-audio-player/blob/mainline/ask-resources.json)
