### ISSUE TITLE
PlaybackController.PlayCommandIssued would result in error

### ISSUE THREAD

**Issue by mfizz1** [alexa/skill-sample-nodejs-audio-player#157]
Unless I am missing something, but wouldn't the following command lead to error since you cannot give a speak directive 

```
if (request.type === 'PlaybackController.PlayCommandIssued') {
      return true;
    }

    if (request.type === 'IntentRequest') {
      return request.intent.name === 'PlayAudio' ||
        request.intent.name === 'AMAZON.ResumeIntent';
    }
  },
  handle(handlerInput) {
    return controller.play(handlerInput);
  },
```

Which in turn would call: 

```
const controller = {
  async play(handlerInput) {
    const {
      attributesManager,
      responseBuilder
    } = handlerInput;

    const playbackInfo = await getPlaybackInfo(handlerInput);
    const {
      playOrder,
      offsetInMilliseconds,
      index
    } = playbackInfo;

    const playBehavior = 'REPLACE_ALL';
    const podcast = constants.audioData[playOrder[index]];
    const token = playOrder[index];
    playbackInfo.nextStreamEnqueued = false;

    responseBuilder
      .speak(`This is ${podcast.title}`)
      .withShouldEndSession(true)
      .addAudioPlayerPlayDirective(playBehavior, podcast.url, token, offsetInMilliseconds, null);
```

But at this stage, you would get the following error:

`The following directives are not supported: Response may not contain an outputSpeech`

**Comment by aszk** [comment]
Your skill can respond to these requests with [AudioPlayer directives](https://developer.amazon.com/en-US/docs/alexa/custom-skills/audioplayer-interface-reference.html#directives) to start and stop playback. In addition, "The response cannot include any of the standard properties such as outputSpeech, card, or reprompt". You need to remove .speak() form your response.
