### ISSUE TITLE
How to listen to the title first and then the audio of the podcast in a list automatically without user request?

### ISSUE THREAD

**Issue by ghost** [alexa/skill-sample-nodejs-audio-player#159]
I have a list of podcasts and I would like to know if when Audioplayer directive has arrived in the playerActivity state: 'FINISHED' afterwards it was possible to automatically Run AMAZON.NextIntent without user request in order to listen to the title first and then the audio of the podcast
E.g. outputspeech:"Wikiradio of today"---> play first podcast --->FINISHED---> outputspeech:"Wikiradio of yesterday"---> play second podcast --->FINISHED--->and so on.

**Comment by mfizz1** [comment]
Don't think that's possible. You cannot send a speak directive with audio player automatically unless invoked by user. Security I guess.

**Comment by aszk** [comment]
mfizz1's answer is correct. There is no way to invoke intents without user's interaction like this use case. You can use [playbackNearlyFinished](https://developer.amazon.com/en-US/docs/alexa/custom-skills/audioplayer-interface-reference.html#playbacknearlyfinished) request to add audio but you can't include outputspeech.
Please give us feedback from [UserVoice](alexa.design/uservoice) if you are interested in adding the function.
