### ISSUE TITLE
Detect end of chapter list

### ISSUE THREAD

**Issue by bartoro** [alexa/skill-sample-nodejs-audio-player#160]
Hello, I want to reproduce a text when the last postcad has been played i. e. "This is the last podcast. Thank you for your attention.". 

For me, the easiest way is to detect the last item in PlaybackNearlyFinished but, since it is not possible to "speak" while in AudioPlayer.PlaybackNearlyFinished, how can I implement it? Any idea?
Thank you!

**Comment by aszk** [comment]
I assume that the message will be spoken by Alexa. If that's the case, it is currently impossible. Like you mentioned, you need to respond AudioPlayer.PlaybackNearlyFinished with play directive that doesn't have outputSpeech. https://developer.amazon.com/en-US/docs/alexa/custom-skills/audioplayer-interface-reference.html#play 
It might not be desired but the skill can notify users when they invoke the skill after the last podcast is played with checking if they played the last podcast.
