### ISSUE TITLE
Session End when in exception so "said help" do not work

### ISSUE THREAD

**Issue by bartoro** [alexa/skill-sample-nodejs-audio-player#161]
Hello, if there is something wrong the method AllExceptionsHandler() is invoked and a speak message offers you to said "help" and finish. At that moment Alexa is no longer running the skill so if I said "Alexa, help" alexa answer but no the answer programmed in HelpIntentHandler(). How can I program it so that if something is not understand and launch AllExceptionHandler if the user saids "Alexa, help" it goes to HelpIntentHandler?

**Comment by aszk** [comment]
I think your question is for old code and new code sample. We updated the code and it doesn't have AllExceptionsHandler anymore. I assume that AllExceptionsHandler set shouldEndSession true. This means your skill session will end after the handler process requests. In the new code, FallbackIntentHandler(similar to AllExceptionsHandler) should set shouldEndSession true and you can keep talking to your skill. You can refer fallbackIntentHandler [here](https://github.com/alexa-samples/skill-sample-nodejs-audio-player/blob/mainline/lambda/index.js#L245) and HelpIntentHanlder [here](https://github.com/alexa-samples/skill-sample-nodejs-audio-player/blob/mainline/lambda/index.js#L108)
