### ISSUE TITLE
Alexa audio skill not showing progress bar while playing audio

### ISSUE THREAD

**Issue by muhammad-ramzan-confiz** [alexa/skill-sample-nodejs-audio-player#162]
I have seen a progress bar in Amazon music skill.
Try **Alexa play music** in echo show for reference. There is a progress bar showing the playtime of audio content.

I am sending audio player directive like below and no playtime information is visible in my echo show.

```
handlerInput.responseBuilder
    .addAudioPlayerPlayDirective('REPLACE_ALL', podcastURL, podcastURL, 0, null, metadata)
    .getResponse();
```

**Comment by aszk** [comment]
The progress bar, as you might see when streaming from Amazon Music on your Echo Show, is not currently a supported feature of the AudioPlayer interface used in custom skills.
