### ISSUE TITLE
Node.js 8.10 not supported

### ISSUE THREAD

**Issue by idkpmiller** [alexa/skill-sample-nodejs-audio-player#163]
Hi,
I may well have made things worse. I followed the instructions. and after successful test suite run I performed an ask deplay.

This seemed to work ok and I went to the web gui of my skill and enabled testing.
I then realised it was not working well.
Going back to the cli I saw that the lamda code had not deployed as the Node.js 8.10 code was no longer supported unsure of how to deal with this I deleted the skill using the web gui.

After some reading I felt like the tsconfig target parameter needed updating and changed it from ES2017 to ES2019 and tried to ask deploy again, now it errors saying:

-------------------- Update Skill Project --------------------
[Error] Skill not found.

I am sure that is because I delted the skill using the web 
GUI but not sure how to correct.

Hoping you can assist
Paul

**Comment by dievaa** [comment]
If you deleted the skill from the Developer Console, the skill does not exist anymore and this is the reason why you are getting that error message.

Therefore, you need to create the skill via CLI again or, alternatively, you can create your audioPlayer skill directly from the Developer Console importing this GitHub repository with the following steps:

1. In the developer console, click to create a new skill
    - On the first page, insert the skill name and choose a primary locale for your skill
2. On the next page, select “Other”, then
    - Select the “Custom” model from the section 2
    - Select "Alexa-hosted (Node.js)" from the bottom section
3. On the next page, click "Import skill". Take this link and place it in the pop-up modal:
    - https://github.com/alexa-samples/skill-sample-nodejs-audio-player.git
    - Save that; your new skill will be created using the code from GitHub.
4. Once the skill has been created, you can take a look at what already exists in the interaction model and the code tab.
