### ISSUE TITLE
Error - Expecting request type of IntentRequest but got AudioPlayer.PlaybackStarted

### ISSUE THREAD

**Issue by balayogesh007** [alexa/skill-sample-nodejs-audio-player#167]
![err_playbackstarted](https://user-images.githubusercontent.com/91451601/221563340-652a014e-e71d-4e64-8180-539787165c88.png)
I go through the docs and some other references but not solved.

**Comment by dievaa** [comment]
In order to investigate your issue further, can you reach out to us via the Contact Us page below and make sure to provide the Skill ID and steps to reproduce the issue.

https://developer.amazon.com/alexa/console/contact-us
