### ISSUE TITLE
Problem with the Skill Response

### ISSUE THREAD

**Issue by youneverknow1** [alexa/skill-sample-nodejs-audio-player#18]
I am very new to whole Alexa skill thing, and I am just following the step by step directions.  After following all the steps (including installing on Alexa Raspberry Pi device) and whole AWS setup, when I issued command "Alexa Audio Player" - I got response "There's problem with the requested skill response".

**Comment by michaelsenn09** [comment]
Hi,
I faced the same issue when I started with this example code and changed the songs list in audioAssets.js. After that I changed the mp3 links and now its working fine.

**Comment by sammyk77** [comment]
I'm getting the same error and have been trying for hours to figure out what is going on. I have the npm files created, the UserID is entered, the DynamoDB table is being created, but I keep getting "There's a problem with the requested skill response." I am using a single valid .mp3 url, but I'm stuck on debugging what to look for. I can view the logs for clues which is what got me to this point, but now it doesn't have any more clues for me. Just "Version: $LATEST". Any help on where to look further would be very much appreciated. In the long run, I'm just looking to stream a single url. Thanks!

The Lambda Response is always:

`{
  "version": "1.0",
  "response": {
    "shouldEndSession": true
  },
  "sessionAttributes": {
    "loop": true,
    "STATE": "_PLAY_MODE",
    "index": 0,
    "offsetInMilliseconds": 0,
    "shuffle": false,
    "playbackIndexChanged": false,
    "playOrder": [
      0
    ]
  }
}`

**Comment by armicron** [comment]
I return the following json and get the same error.
```json
{
	"response": {
		"shouldEndSession": true,
		"directives": [{
			"playBehavior": "REPLACE_ALL",
			"audioItem": {
				"stream": {
					"url": "https://s3-eu-west-1.amazonaws.com/zzzz/zzzz/zzz.mp3",
					"token": "12345",
					"offsetInMilliseconds": 0
				}
			},
			"type": "AudioPlayer.Play"
		}]
	}
}
```

**Comment by chrisnoon74** [comment]
Am getting the same issue, works fine with uploading the initial files. Then when I change the mp3 links (using S3) and have deleted the old Dynamo DB, it wont create a new one

getting problem with the skill response

any thoughts?

**Comment by dsaravana** [comment]
In the Alexa Developer Portal, enable Audio Player Support in the configuration for the Skill, it should solve the issue

**Comment by PardeepWildnet** [comment]
Adding to @dsaravana comment, also song should be https protected , http won't work with alexa

**Comment by PardeepWildnet** [comment]
If anyone can help, is there any way to debug Alexa skill code line by line ?

**Comment by jasonabradley** [comment]
You have a few options. X-Ray under Monitoring if your function can show some detail. Also you can interject console.log statement at various points to log more detail. However if you are using this repo then you’re using NodeJs which is synchronous execution. As such several lines are running at the same time.

Jason
________________________________

**Comment by PardeepWildnet** [comment]
@jasonabradley  Thanku for information, i had put `console.log` at several points but where to check these consoles ? I had checked these on aws logs console but didn't understand, neither `debugger` is working in the case. and can you please explain what is X-ray here ?

**Comment by sebsto** [comment]
AWS Lambda logs can be access through AWS Cloudwatch 
https://docs.aws.amazon.com/lambda/latest/dg/monitoring-functions-logs.html

XRay is an AWS service to trace logs accross multiple AWS services https://aws.amazon.com/xray/

I am closing this thread as it does not appear to be a problem with the code sample, but general programming quetsions.
