### ISSUE TITLE
Syntax error in Test

### ISSUE THREAD

**Issue by bywillyoo** [alexa/skill-sample-nodejs-audio-player#2]
From CloudWatch 

Syntax error in module 'index': SyntaxError at Module._compile (module.js:439:25) at Object.Module._extensions..js (module.js:474:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) at Module.require (module.js:364:17) at require (module.js:380:17) at Object.<anonymous> (/var/task/node_modules/alexa-sdk/index.js:1:88) at Module._compile (module.js:456:26) at Object.Module._extensions..js (module.js:474:10) at Module.load (module.js:356:32)

Configured CloudWatch correctly in IAm - getting this Syntax error. Very sure the folder is zip'd correctly from /js

**Comment by rjamison** [comment]
That seems to be an issue with the wrong NodeJS version being used in Lambda.  I was able to reproduce by selecting "NodeJS" instead of "Node.js 4.3" in the configuration options for my Lambda. 

<img width="576" alt="screen shot 2016-08-26 at 8 31 14 am" src="https://cloud.githubusercontent.com/assets/7671574/18010920/87f7247e-6b67-11e6-9b4a-751cce421704.png">

If you change the configuration, you may encounter a bug that prevents you from changing that property without entering some inline code.  To workaround, just enter some placeholder code (such as `console.log('placeholder');`) when you change the configuration.  Then upload the zip again.

**Comment by bywillyoo** [comment]
@rjamison Already working with 4.3 and installed/zipped node_modules with 4.3 - still getting same issues

**Comment by rjamison** [comment]
Perhaps an issue with the version of NPM or the SDK used?  Here's what I'm using:

``` bash
$ npm -v
3.8.6
$ npm install
skill-sample-nodejs-audio-player@1.0.0 /dev/skill-sample-nodejs-audio-player/js
└─┬ alexa-sdk@1.0.5 
  └─┬ aws-sdk@2.5.3 
    ├── jmespath@0.15.0 
    ├── sax@1.1.5 
    ├── xml2js@0.4.15 
    └─┬ xmlbuilder@2.6.2 
      └── lodash@3.5.0 

npm WARN skill-sample-nodejs-audio-player@1.0.0 license should be a valid SPDX license expression
```

**Comment by vubui** [comment]
This might be because you zip the directory `js` itself but not the content of the directory. I'd suggest you `cd` into the js directory, zip all the files, and update your lambda. Hope this helps.

**Comment by bywillyoo** [comment]
@vubui js is zipped correctly. Understand that System is not defined in Simulator, but using echoism.io I still get the same error in CloudWatch logs 

2016-08-26T16:22:57.991Z    593fd765-6ba9-11e6-92f5-8d9fb7451a83    TypeError: Cannot read property 'System' of undefined at exports.handler (/var/task/index.js:20:22)

**Comment by vubui** [comment]
There is a discussion in the forum here: https://forums.developer.amazon.com/questions/35586/error-with-audio-player-sample-project.html. You can take a look.

**Comment by scottbea** [comment]
The issue I found was that the code in `index.js` throws an error when used in the Lambda Console for Test. This line of code causes problems:

`if (event.context.System.device.supportedInterfaces.AudioPlayer === undefined)`

The Lambda Console does not have an `event.context.System` object, so we are access a property of an undefined object. My fix was simply this:

```
var audioPlayerInterface = ((((event.context || {}).System || {}).device || {}).supportedInterfaces || {}).AudioPlayer;
if (audioPlayerInterface === undefined) {

```

This works fine now in the Lambda Console when performing a test. I'll do a pull request.

**Comment by smile-xuc** [comment]
@scottbea thx so much! It is the right solution about this problem.
