### ISSUE TITLE
Select track by title?

### ISSUE THREAD

**Issue by gmtta** [alexa/skill-sample-nodejs-audio-player#20]
Can anyone provide insight on how you might select a track by title, e.g. "Episode 138" (from the example) instead of just starting from the first one?

**Comment by rsokz** [comment]
What you'll have to do is some sort of loop through the entire audioData array to match the title you're looking for.

E.g.
```
var track;
for (var item in audioData) {
    if (audioData[item].title === 'Episode 138') {
        track = audioData[item].url;
    }
}
```

**Comment by ghimm** [comment]
I believe you need to create a slot and ask for the episode number then loop through the audioData.  I'll see if I can put something together this weekend.

**Comment by ghimm** [comment]
Got it working.  See the solution here:  https://github.com/ghimm/eveningcoffee.git
