### ISSUE TITLE
After removing the Dynamo table, cannot enter play_mode state

### ISSUE THREAD

**Issue by ryandeming** [alexa/skill-sample-nodejs-audio-player#21]
So, I didn't want the functionality of being able to resume. It was getting kind of annoying, so I just removed the table code from the index. However, I can no longer go to next or previous because the player  never leaves the START_MODE state.

This doesn't really make sense to me. Didn't change anything besides removing that one line.

**Comment by rsokz** [comment]
It seems as though the states are reliant on Dynamo table. I had an issue leave PLAY_MODE until I realized I had to add the following line:

`this.attributes['STATE'] = '_START_MODE';`

**Comment by sebsto** [comment]
The Alexa NodeJS SDK is using DynamoDB to store the state across session.  If you don't want to use the DynamoDB table, just remove the name of the table from the skill configuration.
This is documented in the SDK at https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#persisting-skill-attributes-through-dynamodb
