### ISSUE TITLE
NetworkingError: this is not a typed array

### ISSUE THREAD

**Issue by marcelo-marqueti-movile** [alexa/skill-sample-nodejs-audio-player#23]
Hello,

Somebody has the same problem?

I have the setup, but when I call the first action I got this error in debug lambda:

`{
    "message": "this is not a typed array.",
    "code": "NetworkingError",
    "region": "us-east-1",
    "hostname": "dynamodb.us-east-1.amazonaws.com",
    "retryable": true,
    "time": "2017-01-18T03:50:07.433Z"
}`

This format at Alexa console
`{
  "errorMessage": "Error fetching user state: NetworkingError: this is not a typed array."
}`

I already check the permissions, alexa-sdk version and do not found anything related.

Tks!

**Comment by heneryville** [comment]
I've been experiencing a similar issue. It occurs only from within Lambda for me. Still working through what this could be.

**Comment by sebsto** [comment]
It looks like you're trying to persist data into DynamoDB in a format it can not understand.  
The Alexa NodeJS SDK is persisting the content of your Alexa session in DynamoDB automatically for you.  Check the data you have in the session and it will give you a clue about what is going wrong.  Feel free to reopen this, sharing more details about the object in the session if you still are facing this issue.
