### ISSUE TITLE
Audio player directives not supported?

### ISSUE THREAD

**Issue by perrycbrown** [alexa/skill-sample-nodejs-audio-player#27]
From the developer.amazon.com service simulator (after installing/configuring the audio play on my AWS account):

"Note: Service Simulator does not currently support testing audio player directives and customer account linking."

If the audio player can't be tested there, where can it be tested?

**Comment by perrycbrown** [comment]
Figured it out :-)

**Comment by swap357** [comment]
how did you test ?

**Comment by perrycbrown** [comment]
Your Alexa skill _in dev mode_ can be accessed through the Alexa app on your mobile phone (when you login with your Amazon dev credentials), and of course you can then test it through your Echo Dot or similar Alexa product.

**Comment by jimrushPersonal** [comment]
I'm currently having an audio playback issue that exists on the Dot, but not the Echo. I was hoping the simulator would give me better insight into what is actually going wrong.  Maybe in a later version.
