### ISSUE TITLE
please help me zip the project from the CMD...

### ISSUE THREAD

**Issue by drblankenstein** [alexa/skill-sample-nodejs-audio-player#29]
I'm a total github newb. I am having trouble zipping the project. I follow all of your command instruction but when I get to "zip -r ../audio-player.zip *" I am returned 'zip' in not recognized as an internal or external command, operable program or batch file.  I have tried every single way I can think of.  I have everything else set up perfect, I have built Alexa skill before, but can't seem to zip the file correctly from the command prompt and get the skill to work.  Please help, thanks in advance. Thanks for posting!

**Comment by drblankenstein** [comment]
been trying all day, just can't figure out what I'm doing wrong :/

**Comment by nstublen** [comment]
Do you have node-lambda installed?  I use its package function to create my .zip files and it works great.

https://www.npmjs.com/package/node-lambda#package

**Comment by drblankenstein** [comment]
Thanks for getting back to me Neal.

I am sure what I am dealing with is total newb issues, I feel like I'm not
doing something wrong with github. Maybe not sending the zip to the correct
directory, or as you said... something is not installed.  I will take a
look at node-lambda and see if I can get it working.  I included a
screenshot of what I'm seeing when I try to zip the file, maybe you can see
something I don't.

Lastly, if all else fails... is there somewhere I might download the
package directly? Or do you have it off hand you can send to me.


Again... I really appreciate the reply. I am banging my head against the
wall with this one. Thanks!

Drew

**Comment by drblankenstein** [comment]
Neal,

One last, probably obvious note...  I have no problem pulling down the
files to my computer from github, just can't seem to zip them up right for
some reason.  I tried manually zipping them directly, but I am not sure
which files of the bunch I need to include in the zip (not that I really
thought it would be that easy, but it was worth a try). As I said...
totally newb issues :/

Really sorry for bugging you. Any help is very much appreciated, thanks
again for your time.

Drew

**Comment by nstublen** [comment]
Sorry - let me make sure I understand what you've done.

You have the `skill-sample-nodejs-audio-player` files from GitHub on your computer and you're trying to zip them up into an audio-player.zip file (which could then be imported into an AWS Lambda function). Is that correct?

Are you using a Mac or Windows computer?

**Comment by drblankenstein** [comment]
You got it 100%... Sounded simple enough. I must overlooking something
somewhere. Thanks again again for your help.  I really appreciate it.

Drew

**Comment by nstublen** [comment]
I don't believe Windows has a `zip` command. You can try to go the `node-lambda` route, or you can create a .zip file from Windows Explorer by selecting all the files you want to include in the .zip file, right-clicking on one of the selected files, and selecting `Send To` > `Compressed (zipped) folder'.

**Comment by drblankenstein** [comment]
I tried that method, I figured the CMD zipped it differently since the
skill failed in testing. Thanks for clearing that up for me, I was
wondering why I needed to zip from a CMD prompt when I could just zip up
the files manually from the my desktop (what I usually do on GitHub,
because of my newbness lol). But when it didn't work (I tried a bunch of
times, first zipping all the files, next zipping different files I thought
might be part of the project) I then figured I was zipping the wrong files,
or including files that weren't supposed to be there since I keep get a
skill failed error.

All the files of the project on github are to be uploaded in the script
console? *Can you take a screenshot or send a list of the files that are
supposed to be in the zip I upload so I can check them against with I have
here.*  From what you said, it seems I am doing everything right.. but
still getting a skill error when evoked. It makes me feel like I have
zipped up the wrong files or something.

Thanks again so much for your help,

Drew

**Comment by drblankenstein** [comment]
Hi Neal,

Here's the files I'm seeing. I have tried zipping the entire folder, as
well the JS folder, and various other cominations... which files should I
be zipping?


thanks again, hope you are having a good weekend,

Drew

**Comment by nystrup12** [comment]
@drblankenstein did you ever get this figured out (what to zip)? Having similar issue

**Comment by thynn11** [comment]
I had the same issue. First, Windows doesn't have zip command (built-in) and unfortunately most AWS labs and instructions assume we all are using MAC. I resolved it by manually zipping (Windows -> Compress Zip Folder as mentioned above) all the content in js folder. 

If you zip the JS folder itself, it won't work. 

You have to go inside js folder, select all the files in js folder, rightclick and "send to compress zip folder". Upload the zip file.

**Comment by sebsto** [comment]
Thanks @thynn11  for helping!
