### ISSUE TITLE
Play episodes from RSS feed?

### ISSUE THREAD

**Issue by GeekedLife** [alexa/skill-sample-nodejs-audio-player#31]
Is there a possibility to pull episodes from the RSS feed instead of manually entering each file/episode?

**Comment by tukeyclothespin** [comment]
I used 'sync-request' to avoid issues with audioData being undefined on export (regular 'request' is an async call). Then xml2js to parse the rss. It's a hack but it works.

```javascript
'use-strict';  
var request = require('sync-request');  
var xml2js = require('xml2js');  
var audioData;  
var res = request('GET',"http://feeds.feedburner.com/foxnews/podcasts/FoxNewsSundayAudio");  
var parseString = xml2js.parseString;  
parseString(res.getBody(), function(err,result){  
        var raw = result['rss']['channel'][0]['item'][0]['guid'][0]['_'];  
        var url = "https:/" + raw.substring(raw.search("mp3")+3,raw.length+1);  
        var title = result['rss']['channel'][0]['item'][0]['title'][0];  
        audioData = [{"title":title,"url":url}];  
});  
module.exports = audioData;  
```

**Comment by jasonabradley** [comment]
Neat solution. Works only if the rss feed uses https for audio urls.

**Comment by sebsto** [comment]
Correct, Alexa skills playing audio are required to use HTTPS for audio materials.

**Comment by ramseyk39** [comment]
Hello - I got this to work but it is only grabbing the newest episode. How can I get it to grab all the episodes? Thanks

**Comment by sebsto** [comment]
you can navigate between episode by voice with "Alexa next" or "Alexa previous"

**Comment by ramseyk39** [comment]
Thank you for your reply but every time I ask Alexa to do that, it says that I have reached the end of the playlist.

**Comment by ramseyk39** [comment]
With regards to audio files needing HTTPS, I replaced http with https in the raw variable and the first episode played.

**Comment by sebsto** [comment]
Maybe you have only one item in your playlist.  It is difficult to help
without knowing more about the changes you made to the sample code.

**Comment by djhrishi19** [comment]
I tried modifying the audioplayer using the above code... But lambda keeps on showing me a lot of modules missing one by one... eg promise , util-deprecate , asap etc etc... Could you tell me a solution to this? Or upload your own node_modules folder?

**Comment by ramseyk39** [comment]
I uploaded them one by one, it takes a while because there are a lot. I am sure there is a better way tho

**Comment by djhrishi19** [comment]
Thanks for letting me know... At least now I know that it won't go on till infinity... @ramseyk39

**Comment by djhrishi19** [comment]
On installing a lot of modules manually... I'm stuck on this error... "**Cannot read property '_' of undefined**"

**Comment by ramseyk39** [comment]
Depending on your RSS feed, I am using soundcloud so for me to get this line to work:
        var raw = result['rss']['channel'][0]['item'][0]['guid'][0]['_'];  

I had to use this: var raw = result['rss']['channel'][0]['item'][0]['enclosure'][0]['$'].url;

**Comment by djhrishi19** [comment]
var raw = result['rss']['channel'][0]['item'][0]['enclosure'][0]['_'];   My line is similar. I will try replacing the '_' with '$' Thanks!

**Comment by djhrishi19** [comment]
Why did you replace the underscore with a dollar sign? and .url?

**Comment by djhrishi19** [comment]
I check my RSS feed. My link is also in enclosure. So I used the same line given by you @ramseyk39 

But now I'm getting the error **"Cannot read property '0' of undefined"**

**Comment by ramseyk39** [comment]
I Googled the issue and one of the results said to try it and it worked.

**Comment by djhrishi19** [comment]
"enclosure": {
               "@length": "49880169",
               "@url": "https://traffic.libsyn.com/secure/XYZ.mp3"
},

My enclosure is like this. So should I use .url here as well?

**Comment by ramseyk39** [comment]
I would try it. By using .url I didn't have to use this:  
     var url = "https:/" + raw.substring(raw.search("mp3")+3,raw.length+1);

**Comment by djhrishi19** [comment]
So the variable raw stored your url directly?

And so did you substitute url with raw in this line?

audioData = [{"title":title,"url":**url**}];

**Comment by djhrishi19** [comment]
I'm getting this error after doing what you said and I cannot find what this means...

Cannot read property '0' of undefined

**Comment by ramseyk39** [comment]
Basically, the rest looks like this. I had to replace http with https...
     var urlfull = raw; //"http:/" + raw.substring(raw.search("url")+3,raw.length+1);
        var url = urlfull.replace('http:/','https:/');
        var titlefull = result['rss']['channel'][0]['item'][0]['title'][0];
        var title = titlefull.replace('&', 'and');
        audioData = [{"title":title,"url":url}];

**Comment by djhrishi19** [comment]
Didn't you get this error? 
**Cannot read property '0' of undefined**

Cuz my code is similar.  And I'm getting that error.

**Comment by ramseyk39** [comment]
I did at first but now I don't. My only issue is getting the entire rss feed to play. I can only get the latest episode.

**Comment by djhrishi19** [comment]
For that I guess instead of getting title you can get the episode number and store them in audioData. So when user says episode 2 then it will check with audioData.

My code : 
var url = result['rss']['channel'][0]['item'][0]['enclosure'][0]['$'].url;
var episode = result['rss']['channel'][0]['item'][0]['episode'][0];
        MyPodcast = [{"episode":episode,"url":url}];

But I don't know how to get rid of the error  **Cannot read property '0' of undefined**

**Comment by ramseyk39** [comment]
Maybe change episode to title?

**Comment by djhrishi19** [comment]
In RSS feed there is only one <channel> one <item> and many <enclosures>. So why do <channel> and <item> also have [0]?

**Comment by djhrishi19** [comment]
What does the [0] signify? I'm guessing it stores the link as an array?

**Comment by ramseyk39** [comment]
Item 0 is the first or latest episode. If you set URL item to 7 and Title item to 7 it jumps to the 8th episode. I just need to figure out how to increment it...

**Comment by saileshemitrr** [comment]
I am trying to read anchor.fm RSS feed and the JSON object format is different. dont we have same schema definition?
