### ISSUE TITLE
How to Clear Queue

### ISSUE THREAD

**Issue by emmavray** [alexa/skill-sample-nodejs-audio-player#33]
I've used this template to create a bit of a custom player with various playlists.

Sometimes the user picks a new playlist, but the next song is already enqueued. Despite instructing ` this.response.audioPlayerPlay(new-song-data)` the player FIRST plays the old enqueued song, and then moves onto the new playlist.

How can I instruct the player to clear any pending songs?

**Comment by mdusing** [comment]
Did you ever find a solution for this?

**Comment by emmavray** [comment]
@mdusing we did not. The Alexa team has instructed us to send both `token` and `expected previous token` as NULL to fix this issue - curiously, the player actually throws an error when we do so (_"The Play directive requires a token")._ Quite frustrating.

**Comment by sebsto** [comment]
Did you try to pass the CLEAR_ENQUEUED parameter to the Audio Player Play directive ?

https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#play

**Comment by sebsto** [comment]
closing as there is no reply since 50+ days
