### ISSUE TITLE
Translating the AudioPlayer Output

### ISSUE THREAD

**Issue by niklastreml** [alexa/skill-sample-nodejs-audio-player#35]
I wanted to translate the sentences (in stateHandler.js) alexa says to german when i was finished i got the following error when testing the lambda function:
{
  "errorMessage": "Unexpected token ILLEGAL",
  "errorType": "SyntaxError",
  "stackTrace": [
    "Module._compile (module.js:373:25)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/index.js:4:17)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)"
  ]
}
does somebody know how to fix this?  

Edit: Fixed the problem. The mac i am currently working on just changed every ' into a ´or `automatically when i opened it.

**Comment by sebsto** [comment]
Great you figured out how to fix this.  I am closing this thread.
