### ISSUE TITLE
Cannot find module 'alexa-sdk'

### ISSUE THREAD

**Issue by VoidZA** [alexa/skill-sample-nodejs-audio-player#38]
When I'm using the test interface, i keep getting failed Lambda responses: "The remote endpoint could not be called, or the response it returned was invalid."

Here is the request:
```
{
  "session": {
    "sessionId": "xxxxxxxxxx",
    "application": {
      "applicationId": "xxxxxxxxxx"
    },
    "attributes": {},
    "user": {
      "userId": "xxxxxxxxxxxxxxxx"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "xxxxxxxxxxxx",
    "locale": "en-US",
    "timestamp": "2017-05-24T12:18:41Z",
    "intent": {
      "name": "PlayAudio",
      "slots": {}
    }
  },
  "version": "1.0"
}
```

When I go to my Lambda function and clock on "Test", I get a error that it cannot find module 'alexa-sdk'.

Execution result: failed(logs):
```
{
  "errorMessage": "Cannot find module 'alexa-sdk'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:276:25)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/index.js:3:13)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)"
  ]
}

```
I tied to find a way to install the alexa-sdk but I cannot find a way to do it.

Any ideas?

**Comment by VoidZA** [comment]
Downloaded a template when I created a new function in lambda, it had a folder "node_modules", so I added this folder beside the rest of the js files and ziped that, then it worked

**Comment by n2questdev** [comment]
In case anyone had this question.. run _**npm install**_ from the js folder to make sure it installs or updates npm_modules.

**Comment by entpnerd** [comment]
Note that if you are zipping on a Mac, you may still experience issues. Namely, you might still get an error message "Cannot find module '/var/task/index'". For such cases, you need to zip using the command line. See: https://stackoverflow.com/q/41750026/4851565

**Comment by PardeepWildnet** [comment]
@entpnerd  can you please tell me how to resolve "bash-zip: command not found" on windows ?

**Comment by entpnerd** [comment]
Sorry @PardeepWildnet - not sure how to do it on Windows. If you can't get a decent answer here, consider asking on StackOverflow. Also, if you aren't used to asking on SO, consider reading https://stackoverflow.com/help/how-to-ask before you post, lest the SO trolls get you.
