### ISSUE TITLE
Can't play the link starting with http://

### ISSUE THREAD

**Issue by YunyuZhang** [alexa/skill-sample-nodejs-audio-player#39]
I tried to play audio from the link which started with  `http://`, but the Alexa said that the source was not available.

**Comment by xelfer** [comment]
Per https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/custom-audioplayer-interface-reference

audioItem.stream.url:  The audio file must be hosted at an Internet-accessible HTTPS endpoint. HTTPS is required, and the domain hosting the files must present a valid, trusted SSL certificate
