### ISSUE TITLE
constants.appId  and lambda timeout issues

### ISSUE THREAD

**Issue by jeropaul** [alexa/skill-sample-nodejs-audio-player#40]
I encountered a couple of issues getting this running.

1) constants.js has a attribute called appId.  If you follow the readme in order you can't specify the this value until you have started step 3.  Which is after creating and uploading the zip...  Is there another way to get this value?

2) I needed to modify the default configuration for the lambda function to have a longer timeout in order to use the lambda test or echosim.  After the first successful run it ran within a few hundred milli seconds.  Was there something else I could do here?

**Comment by 3mmali** [comment]
How long did you set your timeout for?? I am having the same issue except even at 5 minutes it's still not working..

**Comment by sebsto** [comment]
Alexa timeout is at 8 secs, so configuring Lambda timeout to 7 secs is generally considered as a good practice.

Also, EchoSim will not work to test these skills as Echo Sim does not support audio player directives.  You can only test these on a actual Echo device. 

I am closing it now, feel free to re-open if you're still facing issues.
