### ISSUE TITLE
Audio player is not streaming the podcast in Amazon app provided alexa feature

### ISSUE THREAD

**Issue by mukul4u2005** [alexa/skill-sample-nodejs-audio-player#41]
I am not sure on Iphone's Amazon Alexa feature can stream the music or not, but its play song when I asked "play music". It means streaming.

I just copied all steps which are given in this sample but it is not playing anything after invoking phase like:"Alexa, ask Audio player begin podcase" its listen and then stop. I am not able to see any error in logs. there are only start ,end and report entry.

Could you suggest what can be the reason ?

**Comment by mukul4u2005** [comment]
Could you suggest about this ?

**Comment by n2questdev** [comment]
I had this issue when I first deployed the lambda function. Try echo device itself. It worked on amazon app after that..

**Comment by sebsto** [comment]
We would need more details, such as the full request and response received / sent by your skill.
Look at this code sample on how to capture these.
https://github.com/alexa/skill-sample-nodejs-audio-player/blob/mainline/single-stream/lambda/src/index.js#L11
