### ISSUE TITLE
Lambda Function Code?

### ISSUE THREAD

**Issue by kishan8** [alexa/skill-sample-nodejs-audio-player#47]
Hi, In the screenshot mentioned to upload Lambda Function code but where can I find it?
Thanks,

**Comment by phaniram** [comment]
@kishan8 
What ever that's under https://github.com/alexa/skill-sample-nodejs-audio-player/tree/mainline/js is directly usable for a lambda function (of course you also need to upload node_modules along with that code and few fields in constants.js)

**Comment by sebsto** [comment]
thank you @phaniram for helping !
