### ISSUE TITLE
When opening skill and resume is offered, neither "Yes" or "No" responses are valid

### ISSUE THREAD

**Issue by jasonabradley** [alexa/skill-sample-nodejs-audio-player#48]
When using this as the base for a skill, and saying "alexa, open [skillname]" when an audio file was previously paused, the code offers to resume in Resume_Decision but when answering "yes" or "no" the intent is not triggered as expected.

**Comment by swoodford** [comment]
I also ran into this major bug!  I had to modify `multiple-streams/js/stateHandlers.js` line 83 to remove the `if (this.attributes['playbackFinished']) {` and just default to `this.handler.state = constants.states.START_MODE;` after spending hours trying to debug why it could not handle a yes or no or help response!

**Comment by vinniemo90** [comment]
I ran into this issue as well. However, I noticed that the Yes and No intents were not configured in my interaction model. After adding the intents to my interaction model, the resume state was successfully able to handle the yes and no responses.

**Comment by sebsto** [comment]
@swoodford  I don't think this is a bug and this doe snot seems to be related to yes / no handling.
As @vinniemo90 mentioned, the correct answer is that the skill voice inetrarction model must be updated to support yes / no intent.
Support standard built in intent documentation is at https://developer.amazon.com/docs/custom-skills/standard-built-in-intents.html 

Let us know if more help is needed.

**Comment by swoodford** [comment]
Interesting, that makes sense, but if that's the case shouldn't the `IntentSchema.json` also include Yes/No/Help?  Seems like an oversight that would cause the skill to not work as intended when supporting the ability to resume playback.  It seems no one who developed the skill has tested the skill or done any QA before publishing it which makes it quite frustrating for new Alexa devs attempting to learn and running into errors with the skill sample.

**Comment by sebsto** [comment]
Hell,  I took a deeper look at the Multi Stream sample. Yes, No & Help intent are indeed in the voice interaction model.  Help, Yes and No are also handled at code level, in the dialog state where it makes senses.  For example https://github.com/alexa/skill-sample-nodejs-audio-player/blob/mainline/multiple-streams/js/stateHandlers.js#L145

About the original question : Yes/No not being handled after a "resume?" question : you can see at https://github.com/alexa/skill-sample-nodejs-audio-player/blob/mainline/multiple-streams/js/stateHandlers.js#L88 that the resume question set the state to Resume Decision Mode and the Yes/No are handled and configured to retsrat or reset the player https://github.com/alexa/skill-sample-nodejs-audio-player/blob/mainline/multiple-streams/js/stateHandlers.js#L145

Happy to further help but I would need a step by step description of what is not working (steps to reproduce) 

Seb

**Comment by swoodford** [comment]
Thanks @sebsto I will work to build a new skill from this skill sample and share results if I run into the same problem again.
