### ISSUE TITLE
audio player documentation out of sync with latest code

### ISSUE THREAD

**Issue by thisthatother** [alexa/skill-sample-nodejs-audio-player#49]
Hi I cloned this project a few days ago before there was a multiple streams vs single stream directory structure. the skill I'm trying to build is of the multi-stream variety, but now I don't see a package.json in that subfolder, plus the steps in the README seem a bit off with the actual directory structure, i.e. there is no src/js to zip. can you confirm that the steps are correct? Is the src/InteractionModel the same thing as Intents? Thanks for putting up this example, I'd really like to get it working!

**Comment by sebsto** [comment]
Hello,

Thank you for reporting this, it looks like the multi streams README is an old version, not aligned with the repository structure.  We will fix this asap.

Seb

**Comment by sebsto** [comment]
doc synced now, thank you.  Feel free to close this issue

**Comment by thisthatother** [comment]
Hi Seb,

I don't think you guys have fully addressed the issue. There are still some missing assets and discrepancies between the code in the multiple-streams and the instructions. This issue points some of them out https://github.com/alexa/skill-sample-nodejs-audio-player/issues/50 

I'm happy to close this issue to avoid duplicates, but please address when you can.

Thanks,
Ron
