### ISSUE TITLE
Does DynamboDB Table clean up?

### ISSUE THREAD

**Issue by wschaeferiii** [alexa/skill-sample-nodejs-audio-player#5]
I see that DynamoDB is easily set up and automatically creates tables with the `alexa.dynamoDBTableName = constants.dynamoDBTableName;` in index.js. Does the data and/or tables attached to `this.attributes['foo'] = bar` get cleaned up (deleted) after the alexa app shuts down?  If not, can you point me to some resources where I can set that up?

**Comment by rjamison** [comment]
There's no automatic cleanup process, we wanted to demonstrate how you could use DynamoDB to  persist information about what has been played between sessions, so intentionally store it indefinitely.  The project uses the NodeJS SDK's facility for storing all of the Alexa session attributes to a table.

If you just want to cleanup data, I'd recommend a separate Lambda function you can schedule to delete data from the table on a periodic basis.  You'd also need to add a "last touched" date to the table that you'd use to select which items should be deleted.

Here's example code that deletes a DynamoDB item given a table name and userId:

```
'use strict';
var aws = require('aws-sdk');

function deleteUser(table, userId, callback) {
    doc = new aws.DynamoDB.DocumentClient({apiVersion: '2012-08-10'});
    var params = {
        Key: {
            userId: userId
        },
        TableName: table
    };
    doc.delete(params, function(err, data) {
        if(err) {
            callback(err);
        } else {
            callback(null, data);
        }
    });
}
```

**Comment by jasonabradley** [comment]
Dynamo now supports TTL in the tables, so you could implement directly in Dynamo to expire all keys beyond [x] amount of time.

You can learn more about this feature at https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html

**Comment by nealrs** [comment]
According to the docs, it seems like the TTL attribute has to be set as a top level attribute, not a map attribute. Is there a solution / way to address this? In the node SDK, `this.attributes` is the only way to store data in ddb / but that feeds in `mapAttr`
