### ISSUE TITLE
Quite a few issues with this repo since update

### ISSUE THREAD

**Issue by talkingnews** [alexa/skill-sample-nodejs-audio-player#50]
Hardly any of this seems to be working right now. The multiple-streams folder seems to be missing several folders and files, like package.json

I thought that it was going to be changed to simplify things, but if anything it's more confusing now. The instructions for multiple-streams fail at the second stage (npm install - as package.json is missing).
```
single-stream
  - package.json
  - lambda/
  - .ask/
  - src/
  - test/
  - models/

multiple-streams

  - js/
  - speechAssets/
```

multiple-streams/js/index.js also seems to have some extraneous lines like

```
<<<<<<< HEAD
>>>>>>> 048af9971bc4524114de1045821c7c93f303ffac
```

**Comment by sebsto** [comment]
Thank you for pointing us at this.  We will fix asap
In the meantime, as a workaround, you can remove the lines introducing by merging (<<< and >>>) and type "npm install alexa-sdk" instead of "npm install"

**Comment by akersh-s** [comment]
should be fixed now
