### ISSUE TITLE
Request for example with playlist json pulled from third party source

### ISSUE THREAD

**Issue by talkingnews** [alexa/skill-sample-nodejs-audio-player#51]
Would be great to have an example where the playlist data was pulled from a third party json source, or an s3 bucket full of audio files for example. Thanks

**Comment by sebsto** [comment]
We are trying to keep the samples simple and without dependencies.

This is something you can easily achieve using the AWS SDK for NodeJS : http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/index.html
This SDK is pre-installed on Lambda environment, there is no need to bundle it with your code.

This StackOverflow thread has some code sample.  https://stackoverflow.com/questions/27299139/read-file-from-aws-s3-bucket-using-node-fs
