### ISSUE TITLE
I am facing this in "Test" Sorry, this skill is not supported on this device

### ISSUE THREAD

**Issue by AlgoRepublic** [alexa/skill-sample-nodejs-audio-player#54]

**Comment by sebsto** [comment]
Please provide more details about this issue.  We can not help with just this title.
What are the steps to reproduce, what is the device etc ?

**Comment by debashisde** [comment]
I am facing the same issue. I am trying with "Service Simulator".
Here is my "Service Request":

{
  "session": {
    "new": true,
    "sessionId": "SessionId.*****",
    "application": {
      "applicationId": "amzn1.ask.skill.****"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.*****"
    }
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.****",
    "intent": {
      "name": "PlayAudio",
      "slots": {}
    },
    "locale": "en-IN",
    "timestamp": "2018-01-02T07:16:27Z"
  },
  "context": {
    "AudioPlayer": {
      "playerActivity": "IDLE"
    },
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.****"
      },
      "user": {
        "userId": "amzn1.ask.account.*****"
      },
      "device": {
        "supportedInterfaces": {}
      }
    }
  },
  "version": "1.0"
}


"Service Response" is:

{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "ssml": "<speak> Sorry, this skill is not supported on this device </speak>",
      "type": "SSML"
    },
    "speechletResponse": {
      "outputSpeech": {
        "ssml": "<speak> Sorry, this skill is not supported on this device </speak>"
      },
      "shouldEndSession": true
    }
  },
  "sessionAttributes": {}
}

Please help.

**Comment by sebsto** [comment]
Hello,  
Audio Player directives are not supported on the Alexa developer console simulator.  This is documented at https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#directives :

**Note**: The service simulator does not support testing the AudioPlayer directives or requests.

Please try again from a real device or using the ASK CLI simulation, as described in the README.

**Comment by debashisde** [comment]
Hi, Thank you very much. I will check it out on actual ECHO device.

**Comment by debashisde** [comment]
I confirm this is working fine in ECHO device. Thanks for your help.

**Comment by bpi-hpi** [comment]
It's not working on echo device with testing environment.
