### ISSUE TITLE
I am unable to play this skill on the simulator

### ISSUE THREAD

**Issue by avaadi** [alexa/skill-sample-nodejs-audio-player#55]
Hi,

I am unable to play this audio on the simulator.

It gives me a message "Sorry, this skill is not supported on this device".

It seems the audioplayerinterface is undefined. How do I get rid of this ?

var audioPlayerInterface = ((((event.context || {}).System || {}).device || {}).supportedInterfaces || {}).AudioPlayer;
    if (audioPlayerInterface === undefined) {

**Comment by sebsto** [comment]
"The service simulator does not support testing the AudioPlayer directives or requests."

https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#directives

You need to test from a real device instead

**Comment by Ole73** [comment]
I could run even audio skills on simulator by replacing lines 20-26 in index.js just by alexa.execute();

**Comment by sebsto** [comment]
The skill will run but no audio will play as the web simulator does not have a component to simulate the on-device audio player.  A physical device is needed to test audio skills.
