### ISSUE TITLE
Application Id

### ISSUE THREAD

**Issue by annasxu** [alexa/skill-sample-nodejs-audio-player#57]
I'm running into a lot of issues with the application Id. 
I've tried setting it to alexa.APP_ID, alexa.AppId, alexa.applicationId, but they all either give me: 
Warning: Application ID is not set, or an error about how the application Ids don't match.

**Comment by talkingnews** [comment]
You can safely ignore this message if you want. You only need to set it if you ONLY want that one skill to be able to use your Lambda function.
BUT if you really want to set it to make the errors go away, then you just change it to the skill ID you get from your list of skills, something like: amzn1.ask.skill.123123-123-123123 etc

**Comment by annasxu** [comment]
I'm not too sure what you mean. In constants.js, I already set the appId to something that looks like amzn1.ask.skill.123123-123-123123. Then in index.js I set alexa.AppId = constants.appId. 

And I am getting errors with the application Id: Either that it's invalid or it the amzn1.ask.skill.[unique] doesn't match up. What am I doing wrong?

**Comment by alexhackney** [comment]
There is definitely a problem with setting the appID in the constants, however, you can move forward without setting the id and everything seems to function ok.
