### ISSUE TITLE
Is it possible to play a stream and perform custom interactions with the same skill?

### ISSUE THREAD

**Issue by diegoasef** [alexa/skill-sample-nodejs-audio-player#58]
Hi,
I'm working on a skill that plays radio streams.
I'm trying to offer interactions with my skill while playing the stream.
For example, asking "what is the current show", "what is the current song" or Send a like while listening to the radio.
So far, I can only do this only with a full invocation:
i.e: "Alexa, ask Radio Test what song is playing"
The HelpIntent has the same issue in this example.

It would be great to have direct interactions with an active stream. It has many other use cases.
Is this possible?

Thanks,

**Comment by sebsto** [comment]
Hello,

This is not possible.  While the stream is playing, the session ends, allowing customers to engage with Alexa for something else, like smart home control, weather or engage with another skill.

Amazon forwards to the currently playing skill the "next", "previous", "stop" etc. utterances to allow your skill to control the flow.  But all other utterances must be explicitly directed to your skill : "Alexa, ask my skill what is playing now"

See https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#intents for more details

Seb

**Comment by diegoasef** [comment]
Hi @sebsto,

Thanks a lot for your answer.
I think it would be nice to see in the future additional methods to provide better context for Alexa, like "What is playing"

Thanks,
Diego

**Comment by Ole73** [comment]
I also just recognized, this was my major problem about the last days - and i just began to hate this restriction about the service. It seems like, amazon doesn't think, developer could have further ideas or the capability to write some smooth enhancements up from a CD player functionality...(like: "What is playing") 
So, for now, i have to live with this circumstance, but my navigation will be ugly, therefore. :(

**Comment by akhakiani** [comment]
Hi 
I do not have much developer skills. How do I use this code to play my custom songs on the cloud using Alexa ? 
thanks
Altaj

**Comment by Ole73** [comment]
@akhakiani 
The skill is intended for playing one or more streams by url with public access. You can not easily play own single music titles from a cloud with authorized access. But even with public access, it would only be a workaround to define each song as a single stream, then you could navigate through with the audio commands... but i guess, i would be a pain to enter each url for all songs in a list. And to call each song by name then, you'd also need to enter a slot variable for each title in the alexa service...
Amazon wants you to get a subscription for Amazon music or Spottify - they don't offer practicable ways to get user include their own music for free in any way (did you expect anything else? ;-).. but maybe you could write a connector to Kodi or something like that.. but that would be a quite different skill than this..
