### ISSUE TITLE
Deployement Package of Lembda function on AWS amazon console on Change.

### ISSUE THREAD

**Issue by PardeepWildnet** [alexa/skill-sample-nodejs-audio-player#59]
I am working on one skill using this repo as reference , my query is should i have to create everytime Zip file using command line `zip -r ../audio-player.zip *` on Single word change and then upload to AWS lembda function that zip, this is too much irritating process.

Is there any alternate for the same ?
can i make little changes on lembda function directly on AWS amazon console ?

**Comment by talkingnews** [comment]
As long as you are not importing any libraries, then yes. But if you have already uploaded a zip file, then you will probably not be able to see your code in the code editor. So a better way to do it is to use the ask-cli and use the clone and deploy functions. You can just push the lambda using `ask deploy -t lambda`.

See this guide for info - it might look a bit long, but it is well worth knowing as it will save you hours and lots of frustration in the long run! https://developer.amazon.com/docs/smapi/ask-cli-command-reference.html

**Comment by PardeepWildnet** [comment]
Thanks for the information @talkingnews , but it seems too long process (anyways not read full article yet, will read surely).

Is there anything like let suppose i have made changes in one file so ill update that file instead of uploading full zip file again and test it ?

**Comment by PardeepWildnet** [comment]
@talkingnews , also i am not able to find how to debug the code line by line, is there anything where i can run code line by line and debug it. because it is consuming too much time for development to debug the errors. if possible please put some light here.

Thanks

**Comment by talkingnews** [comment]
The best way is to break the code into small sections, and do what are called "unit tests".

You need to install node locally on your own machine. Anything beyond a basic skill is going to require a good knowledge of javascript. Here are some testing tools I have found:

https://developer.amazon.com/docs/custom-skills/test-a-custom-skill.html

This next tool looks interesting, but not used it yet - it appears to support ElicitSlot, and there's a tracker request for the support of ProggressiveResponse https://github.com/BrianMacIntosh/alexa-skill-test-framework

This looks like a very simple "one file test", which I've used before: https://github.com/alexa/alexa-cookbook/blob/master/labs/Recipe/tests/test.js

ask-CLI and the Skill Simulator API

https://developer.amazon.com/docs/smapi/ask-cli-command-reference.html#invoke-skill-subcommand which, I think, calls this: https://developer.amazon.com/docs/smapi/skill-simulation-api.html

This next one is "a stub lambda function to use to test your Alexa interaction model from your Alexa-enabled device". Handles dialog directives.

https://github.com/alexa/alexa-skills-kit-intent-validator

This is the only other tester I know about which can handle dialogs, but it can't handle dynamoDB-stored states: https://github.com/alexa/alexa-cookbook/tree/master/testing/TestFlow

Not forgetting the VUI Testing Tool: https://github.com/alexa/alexa-cookbook/tree/master/tools/VUI%20Testing%20Tool

**Comment by sebsto** [comment]
In addition to the very well documented answer from @talkingnews, I would like to add that many of us are using VSCode from Microsoft (https://code.visualstudio.com/) This IDE allows to run your unit test locally, to add breakpoints, watch variables etc ...

A sample launch config for VSCode would be 

```json
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
        "type": "node",
        "request": "launch",
        "name": "Single Stream Mocha Tests",
        "program": "${workspaceFolder}/single-stream/lambda/node_modules/mocha/bin/_mocha",
        "args": [
            "-u",
            "tdd",
            "--timeout",
            "999999",
            "--colors",
            "${workspaceFolder}/single-stream/lambda/test"
        ],
        "internalConsoleOptions": "openOnSessionStart",
        "env": {
            "AWS_REGION" : "us-east-1"
        }
    }
    ]
}
```
