### ISSUE TITLE
Newbie : Issues setting this up 

### ISSUE THREAD

**Issue by simonk1969** [alexa/skill-sample-nodejs-audio-player#60]
I'm going through the instructions for prerequisites and setting this up.
So far I've got to the point where I need to 'edit your credentials file on your computer' at this location '%USERPROFILE%\.aws\credentials'  but there is no .aws folder in my profile.
https://developer.amazon.com/docs/smapi/set-up-credentials-for-an-amazon-web-services-account.html
Any ideas why I don't have this folder yet?  I'm running Windows 10.

Is there an easier way to prepare the required files for upload, I just want to create a simple skill with the ability to stream a single audio stream.

Any help much appreciated.
Simon

**Comment by talkingnews** [comment]
Hmm, you shouldn't need to do that. It should have done it for you.
```
npm install -g ask-cli
ask init
```

It should have opened a browser window, you click a link and it configures it for you.

OK, as an alternative, try `ask init --no-browser`

**Comment by simonk1969** [comment]
Initially it did bring up a window and I logged in,  but the instructions I was following said that I needed to manually edit a file.

 

I’ve run ask init --no-browser and it shows my profile name and beside that says Associated AWS Profile  ** NULL **

**Comment by talkingnews** [comment]
Hmmm, not sure then. I'm turning PC off now for the night, but you might have more luck asking this question on the forums. https://forums.developer.amazon.com/spaces/165/index.html

Also, there is the Alexa Slack Channel - it's independently run and more developer-y, and better for short, simple questions as it's sort of like a live chat. http://www.alexaslack.com/

**Comment by sebsto** [comment]
Closing this as this is not related to the code sample.  @talkingnews pointed you towards the correct forums to ask these questions.
