### ISSUE TITLE
Skill don't start

### ISSUE THREAD

**Issue by stfngrf** [alexa/skill-sample-nodejs-audio-player#64]
I install it step by step like in the tutorial.
If i wanna start the skill, alexa always said: There is a problem, starting the skill ... 

The Service Response is
"The remote endpoint could not be called, or the response it returned was invalid."

How can I fix this?

**Comment by sebsto** [comment]
Hello,

Did you try the multiple stream (podcast) skill or the single stream (live radio) skill ?

This message indicates either Alexa can not invoke your lambda function or the function returns an incorrect response.

Few things to check 

- In the Alexa developer console, is the Lambda ARN correct ?
- In the AWS Lambda console, did you authorise Alexa to call your function (Alexa Skill trigger)

Cheers

**Comment by steffenprey** [comment]
Hello,

I have exactly the same problem with the multiple stream (podcast) skill. Is there anyone, who can help me to solve this problem, perheps with tools like TeamViewer, so that I can show you something?

Thanks a lot!

**Comment by sebsto** [comment]
This message indicates either Alexa can not invoke your lambda function or the function returns an incorrect response.

Few things to check

- In the Alexa developer console, is the Lambda ARN correct ?
- In the AWS Lambda console, did you authorise Alexa to call your function (Alexa Skill trigger)
- Is your lambda function called at all ?  Do you receive JSON request from Alexa ?

If you are new to Alexa or Lambda, I would suggest you to follow a tutorial first.  For example https://github.com/alexa/skill-sample-nodejs-city-guide

Seb

**Comment by glennglennglenn** [comment]
@stfngrf  @steffenprey  I bet that you just need to add your app ID to your constants.js file.
See this line:
  // App-ID. TODO: set to your own Skill App ID from the developer portal.
Add your appID below. 

You can get your App ID (aka skill ID) by going to [this link](https://developer.amazon.com/edw/home.html#/skills) and clicking on "view skill ID".
