### ISSUE TITLE
Two different Skills

### ISSUE THREAD

**Issue by jeremywj** [alexa/skill-sample-nodejs-audio-player#66]
I am trying to create a second skill for another stream I run independant of the first.  I believe the second skill is overwriting the lambda function of the first one.  How can I have the second create a new lambda in AWS?

**Comment by sebsto** [comment]
If you're pulling this repo twice, two skills will be created with two lambda functions.
If you copied the files from the first skill, the behaviour you're observing is expected.
The lambda function name is located in ```..ask/config``` directory of your project, be sure to change the lambda function name to another name.

```json
"apis": {
            "custom": {
              "endpoint": {
                "uri": "ask-custom-myradio-default"
              }
            }
          }
```

**Comment by sebsto** [comment]
Closing because lack of activity since several months.  Feel free to reopen if you still have a problem with this.
