### ISSUE TITLE
how to get offset for resume play

### ISSUE THREAD

**Issue by nealrs** [alexa/skill-sample-nodejs-audio-player#68]
Hiya! I'm adapting this skill to support resume, but I don't understand how to get and passback the offset parameter to the play directive.

With Flask-Ask, I think you get this for free -- and I'm new to node. Appreciate any help.

**Comment by sebsto** [comment]
In the Play Directive, you can use the `offsetInMilliseconds` parameter, as per https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#play

When the stream stops playing, you can capture the current offset in the same parameter received in the Playback Stopped request.
https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#playbackstopped
