### ISSUE TITLE
Playlist boundary messages cause errors, and hang with PlaybackController

### ISSUE THREAD

**Issue by talkingnews** [alexa/skill-sample-nodejs-audio-player#71]
In the following code from:
https://github.com/alexa/skill-sample-nodejs-audio-player/blob/mainline/multiple-streams/js/stateHandlers.js#L234
```
 if (index === -1) {
                if (this.attributes['loop']) {
                    index = audioData.length - 1;
                } else {
                    // Reached at the end. Thus reset state to start mode and stop playing.
                    this.handler.state = constants.states.START_MODE;

                    var message = 'You have reached at the start of the playlist.';
                    this.response.speak(message).audioPlayerStop();
                    return this.emit(':responseReady');
                }
            }
```

If you turn looping off and say "Alexa previous" while on the last track, you will indeed get the message about being at the end, but an error will appear in the log. If you try and use a physical control device, an error will also be thrown and no speech is returned, because you are trying to say something in response to an audioplayer command. 

Given the following exception handler:

```	
'System.ExceptionEncountered': function () {
			console.log(`System.ExceptionEncountered. State: ${this.attributes.STATE} type: ${this.event.request.type}  player activity: ${this.event.context.AudioPlayer.playerActivity} offset: ${this.event.context.AudioPlayer.offsetInMilliseconds}` + JSON.stringify(this.event.request.error));
		}
```

then one or other of these two conditions show in the log 

```
{
    "type": "INVALID_RESPONSE",
    "message": "The following directives are not supported: Response may not contain an outputSpeech,Response may not contain an reprompt,Response may not have shouldEndSession set to false"
}
```

or

```
{
    "type": "INVALID_RESPONSE",
    "message": "No response is allowed for the event."
}
```

~Useful though it is to have this response,  sadly it appears that the only valid response to these "start" and "end" conditions is `this.response..audioPlayerStop();` and not `this.response.speak(speechOutput).audioPlayerStop();` unless anyone can think of a good workaround?~

Edit: It actually looks like no response at all is allowed, so I am uncertain how this can be handled without an error being thrown?

More info about this state is also given in this reply,
https://github.com/alexa/skill-sample-nodejs-audio-player/issues/67#issuecomment-359757129

**Comment by sebsto** [comment]
There are two different types of possible responses, depending on the event received.

When your skill does receive a builtin intent such as stop, pause, loop on, previous, etc .
https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#intents
YOU CAN return a TTS alongside to your audio player directive.  

When your skill receive an audio event (playback nearly finished, playback stopped) etc ...
YOU CAN NOT return a TTS, just audio player directive.

For further debugging of your issue, please share the full JSON request received by the skill and the full JSON response your skill is sending to Alexa.  To capture full JSON requests and responses, have a look at this code https://github.com/alexa/skill-sample-nodejs-audio-player/blob/mainline/single-stream/lambda/src/index.js#L11

**Comment by sebsto** [comment]
Closing as there is no more activity since 6 months
