### ISSUE TITLE
How to modify Alexa Audio Player Sample Project to play a specific track

### ISSUE THREAD

**Issue by aaljaali** [alexa/skill-sample-nodejs-audio-player#74]
How to modify Alexa Audio Player Sample Project to play a specific track?

**Comment by sebsto** [comment]
I would suggest to design a dialog to ask the user what he wants to do.  See our Alexa Voice User Experience Design code and other code sample to get started. 
This is similar to this issue : https://github.com/alexa/skill-sample-nodejs-audio-player/issues/73
