### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by adi701** [alexa/skill-sample-nodejs-audio-player#76]
![capture](https://user-images.githubusercontent.com/33590651/36071432-3b7fd510-0f34-11e8-8335-5a39b5e06acf.PNG

Can someone tell me what this error is .

**Comment by bobuehlein** [comment]
That's only part of the error... but I'd look at your files and look for "ar Alexa". I thought that should be var Alexa.

**Comment by adi701** [comment]
that's what i thought at first but that's not it  . I have uploaded my entire zip file.

It would mean a lot if you can go through it and tel me what's wrong 
 
[player.zip](https://github.com/alexa/skill-sample-nodejs-audio-player/files/1718346/player.zip)

**Comment by bobuehlein** [comment]
Is this going to be for multiple audio clips or a single stream source?

One thing I notice... I don't see any of the nodejs files.  Did you run: npm install?

**Comment by adi701** [comment]
the code is for multiple stream 

![prob](https://user-images.githubusercontent.com/33590651/36155054-592b8d4a-10f9-11e8-926d-6dcd03b8c632.PNG)
 
i have attached the new error encountered after fixing the first one i have updated the appid but still it shows the application value is invalid 

[js.zip](https://github.com/alexa/skill-sample-nodejs-audio-player/files/1720246/js.zip)

this is the new source code after including node modules

Thank you

**Comment by sebsto** [comment]
The error comes from the code.  The skill ID you mentioned in your code is not the actual skill ID. 
Please copy paste the correct app id at https://github.com/alexa/skill-sample-nodejs-audio-player/blob/mainline/multiple-streams/js/constants.js#L6

**Comment by adi701** [comment]
hi 

I have cross checked the above file with my application id and my test cases also .

i am getting the same error again and again 

i have uploaded my new source file 

[js.zip](https://github.com/alexa/skill-sample-nodejs-audio-player/files/1730025/js.zip)


thanks

**Comment by sebsto** [comment]
OK, you have the App ID in the code, but do you have the same App ID in the JSON request you're sending to the code ?  What is your JSON in the Lambda Test console ?

**Comment by adi701** [comment]
![capture](https://user-images.githubusercontent.com/33590651/36307821-ee77e744-1343-11e8-8d45-9504a470f927.PNG)

This is the test JSON

**Comment by sebsto** [comment]
Did you made any progress on this one ?  I would suggest to read the log and find / understand any error message throw there.
Another suggestion is to write a small wrapper to call your code locally - it is easier to debug when running from your laptop and the error message are easier to capture.  You can read an example in the unit test of the single stream example : https://github.com/alexa/skill-sample-nodejs-audio-player/tree/mainline/single-stream/lambda/test

**Comment by adi701** [comment]
Thanks for the help . I found a way to bypass the application id problem

**Comment by sebsto** [comment]
That's a great news.  Would you mind to share it here to help others that would have the same problem ?

**Comment by sebsto** [comment]
Closing because lack of activity since several months.  Feel free to reopen if you still have a problem with this.
