### ISSUE TITLE
"errorMessage": "Cannot find module '/var/task/index'"

### ISSUE THREAD

**Issue by pvamsik** [alexa/skill-sample-nodejs-audio-player#77]
I have followed the instructions mentions in many of the threads and uploaded the zip file for the lambda function. 

1. Opened js folder in command prompt
2. Ran npm install
3. zipped the folder using 7zip
4. Uploaded zipped folder

When I test the function with input, I am getting the following error attached. Can someone help please. 

![lambda management console](https://user-images.githubusercontent.com/2813702/36078483-de92144c-0f44-11e8-8121-31c5da00fa3c.png)

Thanks
Vamsi

**Comment by adi701** [comment]
This is because you have zipped the folder rather than the files . 

Soln: select all the files and press add to archive 

Hope it helps

**Comment by pvamsik** [comment]
Thank you @adi701. I finally figured this out last night and was able to proceed.

**Comment by alpeshinfogain** [comment]
@pvamsik .. How did you troubleshoot this?
