### ISSUE TITLE
Skill not working properly when set up

### ISSUE THREAD

**Issue by Beady1997** [alexa/skill-sample-nodejs-audio-player#78]
I'm very new to all of this but excited to learn as I just need skills that aren't out there. I just thought, 'you know what, I'l make them myself'. Anyway, sorry for the rambling, I followed all of the steps and I get to testing the app. I can say 'open audio player' and it gives me welcome message but after that I return with the following 'play audio' command and nothing happens; it just gives me the Alexa not valid sort of tone. I've taken a screenshot of the testing, below. Please help, thanks. 
![screen shot 2018-02-20 at 23 18 28](https://user-images.githubusercontent.com/36680491/36454769-2f970abc-1695-11e8-9199-bd7c6ff2a2a9.png)

**Comment by bobuehlein** [comment]
Do you have a device to test on? It might be working there, but won't work on the tester there. You could also look at the json response and see if its playing/doing what you expected there.

**Comment by Beady1997** [comment]
I’ve tested it on my device and it returns the same response. In regards to the code, I can view it for the commands accept for the one returned after my ‘play audio’ command - it doesn’t show any at all, in that screen shot I’m clicked on audio only response.

**Comment by sebsto** [comment]
Please log and share the full JSON request and response to get more help.

**Comment by johnprakashgithub** [comment]
I do have the same issue only the LaunchRequest works and all other intents are not working

**Comment by sebsto** [comment]
@johnprakashgithub  Please log and share the full JSON request and response to get more help.

**Comment by sebsto** [comment]
Also, the screenshot above shows you're testing on English (GB).  Until yesterday, the code sample had voice interaction model for English (US) only.  Be sure to test in a language supported by the skill.

I added en_GB locale to the code sample yesterday.

**Comment by sebsto** [comment]
Closing because lack of activity since several months.  Feel free to reopen if you still have a problem with this.

**Comment by frunny** [comment]
Having the same issue. Every time I try to build a skill. I never got it to work so I droped Alexa Skill development for now.

**Comment by sebsto** [comment]
@frunny I am happy to help if you can share more details about the specific issue you're facing.  I am afraid "it does not work" is not specific enough to be actionable :-) Feel free to open a new issue and share your error messages, as detailed as possible.

**Comment by frunny** [comment]
Thanks, basicly the invocation always works and the launchRequestHandler
will be fired fine - but any further intent from the user does not return
what it should be. It only says <Audio only response> with a beep. I must
say that I only test this on the Simulator on my Desktop Mac and never did
test this on a real device. I get an Echo Dot today.

When I ran a test in the Lamba Console I get a TypeError -> "Cannot read
property 'locale' of undefined". My Desktop Mac is set to english and the
Skill is created for German. Could this be the problem?

**Comment by sebsto** [comment]
> It only says <Audio only response> with a beep. I must
> say that I only test this on the Simulator on my Desktop Mac and never did
> test this on a real device. I get an Echo Dot today.

This is expected and not an issue.  The skill simulator does not support audio directive.

> When I ran a test in the Lamba Console I get a TypeError -> "Cannot read
> property 'locale' of undefined". My Desktop Mac is set to english and the
> Skill is created for German. Could this be the problem?

This is another problem, an object is null or undefined and causes this error.  It can be traced by understanding what is the request received by the lambda.  Adding a couple of `console.log()` statement will help to trace the cause of this.

Let us know

**Comment by frunny** [comment]
> The skill simulator does not support audio directive.

Hm, not fully understand what you mean with this, I didn't start any audio, only a tell command.

> Adding a couple of console.log() statement will help to trace the cause of this.

Where will I see the console.log output. I added a few but I couldn't see the output.

Thanks!

**Comment by RoyKiran** [comment]
I changed my skill invocation word and the problem solved... I really don't know why was that!

**Comment by kache77** [comment]
The Alexa Simulator **does not render the audio playback,** but the Skill I/O section shows the AudioPlayer directives sent from your skill.

Since the playback does not occur, you cannot test AudioPlayer requests that are triggered by events in the playback, such as PlaybackNearlyFinished.

https://developer.amazon.com/docs/devconsole/test-your-skill.html#pre-built-model-minimum-configuration

**Comment by Prach1810** [comment]
I'm having the same issue . my skill is not even invoking when i say start "Skill name"

**Comment by gauravsoni1** [comment]
> I'm having the same issue . my skill is not even invoking when i say start "Skill name"

Facing the same issue, it keeps loading forever
