### ISSUE TITLE
ask deploy fails

### ISSUE THREAD

**Issue by Flashsolutions** [alexa/skill-sample-nodejs-audio-player#83]
Get the following error when trying to deploy the sample skill with the ASK cli...

Invalid json: /Users/Larry/Downloads/ALEXA/skill-sample-nodejs-audio-player-mainline/multiple-streams/.ask/config

**Comment by DancinDirk** [comment]
I had the same issue, There was an error in the JSON.
Fixing the JSON allowed me to proceed but then the next step failed as well.
Can someone fix the ask deploy so that this works without error?

incorrect code is missing a }
Corrected:
`{
  "deploy_settings": {
    "default": {
      "skill_id": "amzn1.ask.skill.47a4720d-51d3-4c2d-a85b-e2cd993ccf16",
      "was_cloned": false,
      "merge": {
        "manifest": {
          "apis": {
            "custom": {
              "endpoint": {
                "uri": "ask-custom-Multi_Stream_Audio_Player"
              }
            }
          }
        }
      }
    }
  }
}
`

**Comment by DancinDirk** [comment]
I just tried it again from a different machine. With the above JSON change it worked.
I would highly recommend updating the readme.md steps be revised to include the steps to setup and configure AWS-CLI before doing ask init and ask deploy. I think trying to do ask init before aws configure was the second problem I was referencing.

**Comment by sebsto** [comment]
Thank you Dirk.  I uploaded a sample .ask/config file to the repo to avoid this to reproduce in the future. Thank you for your contribution
