### ISSUE TITLE
Audio streaming stop after 30 mins

### ISSUE THREAD

**Issue by legendarykb71** [alexa/skill-sample-nodejs-audio-player#89]
I have this Radio streaming alexa skill. Audio streaming works fine but after 30 mins, stream suddenly stops. And i could see this log on the cloudwatch. What could have cause this? or is there any settings that i need to configure? Thanks 

Please cloudwatch log on the screen shot.
<img width="1438" alt="screen shot 2018-04-01 at 9 02 37 pm" src="https://user-images.githubusercontent.com/28532262/38175608-3965473c-35f0-11e8-9517-049a211dbaa3.png">

**Comment by sebsto** [comment]
Hello,

I don't see an error in the cloudwatch log screenshot you attached.  Do you still experience this issue ?

Seb

**Comment by legendarykb71** [comment]
Hi,

Just tested my Alexa Radio Streaming skill. And now it works fine. Did you
do any fix? or Whats the cause of error?

Thanks,
Kristian Babiera

On Sat, Jun 9, 2018 at 1:07 AM, Sébastien Stormacq <notifications@github.com

**Comment by sebsto** [comment]
No. I did not change anything after having migrated the code to our SDK v2. 
I would assume it might have been an error from the stream or from the on device audio player. Devices gets updated regularly with new firmware. 

--Seb

**Comment by legendarykb71** [comment]
I will check that also. The skill is now playing for almost 6 hours already. Thank you so much. Cheers!
