### ISSUE TITLE
Error: Requested Resource Not Found

### ISSUE THREAD

**Issue by mikeweller13** [alexa/skill-sample-nodejs-audio-player#9]
Hi-

I've tried getting this project to run several different times but keep running into problems. I'm currently stuck with a "Requested resource not found" error when testing in Lambda. I've switched to the exact NPM version that @rjamison shows in his response to issue 2 below and also tried to install the exact module versions that he lists, but still seem to be having the problem. Am I missing a configuration somewhere in AWS? Any help is much appreciated, error message copied from Lambda below. Thanks!

{
  "errorMessage": "Requested resource not found",
  "errorType": "ResourceNotFoundException",
  "stackTrace": [
    "Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:43:27)",
    "Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)",
    "Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)",
    "Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:668:14)",
    "Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
    "AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
    "/var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
    "Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
    "Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:670:12)",
    "Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)"
  ]
}

**Comment by mikeweller13** [comment]
I looked more closely and my issue seems identical to #6 below. I was able to invoke the skill using the Alexa emulator and it was able to create the database, now it is not throwing any errors. Audio Streaming doesn't appear to work on the emulator, so I will try the still from my Echo later today. Sorry for the duplication.

**Comment by JAYESHBHUT** [comment]
{
  "errorMessage": "Requested resource not found",
  "errorType": "ResourceNotFoundException",
  "stackTrace": [
    "Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:48:27)",
    "Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)",
    "Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)",
    "Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)",
    "Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
    "AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
    "/var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
    "Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
    "Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)",
    "Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)"
  ]
}


Tired of errors since last few days. cannot find solution, have anyone idea? this is a nodejs audio player skill.
tried index.zip with windows and commandline but no luck.
tried different directory file combination still no luck.
can any one help ?
i am going to make a audio play skill with 
multiple mp3 file
with pause, resume, stop, next, previous, perticular song etc.
play list
album list etc

**Comment by yashvenrakumar** [comment]
2022-10-04T17:42:12.453Z	2493d49a-194f-40be-8b59-4f0106b0208d	ERROR	Invoke Error 	{
    "errorType": "ResourceNotFoundException",
    "errorMessage": "Requested resource not found",
    "code": "ResourceNotFoundException",
    "message": "Requested resource not found",
    "time": "2022-10-04T17:42:12.450Z",
    "requestId": "4NHJLNBEBFFRF4SEVVM8L1L183VV4KQNSO5AEMVJF66Q9ASUAAJG",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 10.457312478397963,
    "stack": [
        "ResourceNotFoundException: Requested resource not found",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
}


Kindly help me to fix the issue
