### ISSUE TITLE
At end of multistream queue, PlaybackNearlyFinished event triggers System.ExceptionEncounter request

### ISSUE THREAD

**Issue by alexapam** [alexa/skill-sample-nodejs-audio-player#91]
// In audioEventHanders, PlaybackNearlyFinished
var enqueueIndex = this.attributes['index'];
        enqueueIndex +=1;
        // Checking if  there are any items to be enqueued.
        if (enqueueIndex === audioData.length) {
            if (this.attributes['loop']) {
                // Enqueueing the first item since looping is enabled.
                enqueueIndex = 0;
            } else {
                // Nothing to enqueue since reached end of the list and looping is disabled.
                return this.context.succeed({}); // ==> **Causes System.ExceptionEncounter to be returned**
            }
        }

Changing the above line to resolves the issue:
this.emit(':saveState', true);
return;

Can anyone explain why this is?

Thanks

**Comment by sebsto** [comment]
Hello, 

Sorry to hear you;re facing issues with our code sample.  we just migrated the code to the new Alexa SDK for NodeJS v2.  The code has been significantly modified.  

Can you test again with the new code base and report back ?

Thank you !
