### ISSUE TITLE
Response JSON is not being logged

### ISSUE THREAD

**Issue by shyamu** [alexa/skill-sample-nodejs-audio-player#92]
For the multistream player.

In CloudWatch, when running this skill I am only seeing the Request JSON being logged. 

Seems like the [callback](https://github.com/alexa/skill-sample-nodejs-audio-player/blob/1da04690933aab0a2711be6075becf67004a1896/multiple-streams/lambda/src/index.js#L25) to log the Response JSON is never invoked since I am not seeing the 
`******************* RESPONSE **********************` line logged either.

I noticed that the callback was not being passed to Alexa [on this line](https://github.com/alexa/skill-sample-nodejs-audio-player/blob/1da04690933aab0a2711be6075becf67004a1896/multiple-streams/lambda/src/index.js#L9) so I changed it to
`var alexa = Alexa.handler(event, context, callback);` but that didn't seem to fix it. 

Is there any other setup that needs to be done to see response payloads in CloudWatch?

**Comment by sebsto** [comment]
Thank you for your pull request, we have included your change in the new code supporting the Alexa SDK for NodeJS v2
