### ISSUE TITLE
ask deploy fails with Error Code 400

### ISSUE THREAD

**Issue by kstreepy** [alexa/skill-sample-nodejs-audio-player#95]
I receive this error when attempting to deploy:

Error code: 400
{
  "message": "Skill manifest is not valid.",
  "violations": [
    {
      "message": "Invalid skill information."
    }
  ]
}

**Comment by MartinParis** [comment]
This is my skill.json file.
I only changed to invocation.
{
  "manifest": {
    "publishingInformation": {
      "locales": {
        "en-US": {
          "summary": "Very basic podcast sample",
          "examplePhrases": [
            "Alexa, open dance music",
            "Alexa, start",
            "Alexa, stop"
          ],
          "keywords": [
            "podcast",
            "streaming",
            "example"
          ],
          "name": "Multi Stream Audio Player",
          "description": "",
          "smallIconUri": "https://alexademo.ninja/skills/logo-108.png",
          "largeIconUri": "https://alexademo.ninja/skills/logo-512.png"
        },
        "en-GB": {
          "summary": "Very basic podcast sample",
          "examplePhrases": [
            "Alexa, open dance music",
            "Alexa, start",
            "Alexa, stop"
          ],
          "keywords": [
            "podcast",
            "streaming",
            "example"
          ],
          "name": "Multi Stream Audio Player",
          "description": "",
          "smallIconUri": "https://alexademo.ninja/skills/logo-108.png",
          "largeIconUri": "https://alexademo.ninja/skills/logo-512.png"
        }
      },
      "isAvailableWorldwide": true,
      "testingInstructions": "Include your testing instruction (if any) here",
      "category": "STREAMING_SERVICE",
      "distributionCountries": []
    },
    "apis": {
      "custom": {
        "endpoint": {
          "sourceDir": "lambda/src"
        },
        "interfaces": [
          {
            "type": "AUDIO_PLAYER"
          }
        ]
      }
    },
    "manifestVersion": "1.0",
    "permissions": [],
    "privacyAndCompliance": {
      "allowsPurchases": false,
      "isExportCompliant": true,
      "containsAds": false,
      "isChildDirected": false,
      "usesPersonalInfo": false
    }
  }
}

**Comment by bobuehlein** [comment]
I know this is kinda old... but It look me the longest time to realize that amazon added a language to my live skills, that I wasn't including in my skill manifest. Could check that.

**Comment by sebsto** [comment]
Thank you for having provided feedback, closing this issue.
