### ISSUE TITLE
Getting the Error AudioPlayer is currently an unsupported namespace

### ISSUE THREAD

**Issue by Sumanth1988** [alexa/skill-sample-nodejs-audio-player#96]
Hi ,

I have setup and able to run the code , i have configured my own media files in S3.When the audio is supposed to be played , i get this error. 

<img width="453" alt="screen shot 2018-04-10 at 2 51 14 pm" src="https://user-images.githubusercontent.com/38234341/38583147-bf964df4-3cd7-11e8-88fa-666b0b57e4b1.png">

**Comment by MartinParis** [comment]
Which is not an error, audioplayer functionality is not supported in the test function through the browser. Just run the skill on an actual device and see if it works. If not, check the cloudwatch logs.
Error I made, not referencing the audio files through https. You will also learn that from the logs.
Happy playing!

**Comment by Sumanth1988** [comment]
@MartinParis Thanks for the info, Is there a procedure to link your echo device for development?My device is for generic use.

**Comment by MartinParis** [comment]
Nope, every skill you make is , after being build, automagically available on your device. At least that is how it is for me a device linked to my account, the same as I made the skill in. That is the requirement I guess for this.

**Comment by Sumanth1988** [comment]
I got my skill working on the device,Thank you very much for your help.

**Comment by MartinParis** [comment]
Cool, it took me some time as well :-). As a noob with node.js.....

**Comment by MartinParis** [comment]
Can you close this issue?

**Comment by hide-G** [comment]
I was in trouble because it was in the same state. It was very helpful. Thank you very much!

**Comment by gijoevaldez** [comment]
Can someone post a solution to this? Or is trying it on your device the answer? I'm trying it on my phone as I'm developing on my PC.
